2019-3-14
Esukhia/derge-tengyur pull request #1
Opened 2019-03-14 11:23 UTC by kunchokdolma

2019-03-14 11:30 UTC, tseringwa approved these changes

2019-03-14 11:31 UTC, tseringwa approved these changes

2019-03-14 14:22 UTC, ngawangtrinley commented on text/170_འཁྲི་ཤིང།_ཀེ.txt
> +[89a.3]སུ་བྷ་དྲཾ་བྷ་ག་བཱན་སརྦ་བྷུ་ཏ་ཧི་ཏེ་ར་། །བ་བྷཱ་ཥེ་བིསྨ་ཡོཏ་བྷྲཱནྟཾ་པུ་ཏྲོ་ཡཾ་གྲྀ་ཧྱ་ཏཱ་མི་ཏི། །ས་ཏུ་དོ་ལཱ་ཀུ་ལ་མ་ཏིཿཀིཾ་ཀ་རོ་མཱི་ཏི་སཾ་ཤ་ཡཱཏ། །ཀྵ་པ་ཎཱ་ནཱོཾ་མུ་ཁཱ་ནྱེ་བ་ཤིཀྵཱ་ཡཻ་ཀྵ་ཎ་མཻ་ཀྵྱ་ཏ། །ཏེ་ཏ་
![image](https://user-images.githubusercontent.com/17675331/54364328-a304e300-46a7-11e9-8ff6-b0da8b4cb463.png)

2019-03-15 14:21 UTC, rekongrabten requested changes
འདི་དག་བསྐྱར་དུ་ནན་གཟིགས་གནང་རོགས།

2019-03-15 14:21 UTC, rekongrabten commented on text/009_རྒྱུད་འགྲེལ།_ཉ.txt
> +[242a.1]༄༅། །ཏྲཱ་ཡ་ན་མཿ། ཨོཾ་ཥོ་ཌ་ཤ་བྷུ་ཛཱ་ཡ་ན་མཿ། ཨོཾ་ཀྲྀ་ཥྞ་ཛཱི་མཱུ་ཏ་ཝ་པུ་ཥེ་ན་མཿ། ཨོཾ་ཀ་པཱ་ལ་མཱ་ལཱ་ནེ། ཀ་དྷ་རི་ཎེ་ན་མཿ། ཨོཾ་ཨ་དྷྨ་ཏ་ཀྲཱུ་ར་ཙི་ཏྟཱ་ཡ་ན་མཿ། ཨོཾ་ཨ་རྡྷེ་ནྡུ་དཾ་ཥྛ་ཎེ་ན་མཿ། དེ་ནས་ཡང་།
འདིའི་ཐིག་མགོའི་དབུ་ཁྱུད་དེ་མི་དགོས།

2019-03-15 14:21 UTC, rekongrabten commented on text/170_འཁྲི་ཤིང།_ཀེ.txt
> +[89a.3]སུ་བྷ་དྲཾ་བྷ་ག་བཱན་སརྦ་བྷུ་ཏ་ཧི་ཏེ་ར་། །བ་བྷཱ་ཥེ་བིསྨ་ཡོཏ་བྷྲཱནྟཾ་པུ་ཏྲོ་ཡཾ་གྲྀ་ཧྱ་ཏཱ་མི་ཏི། །ས་ཏུ་དོ་ལཱ་ཀུ་ལ་མ་ཏིཿཀིཾ་ཀ་རོ་མཱི་ཏི་སཾ་ཤ་ཡཱཏ། །ཀྵ་པ་ཎཱ་ནཱོཾ་མུ་ཁཱ་ནྱེ་བ་ཤིཀྵཱ་ཡཻ་ཀྵ་ཎ་མཻ་ཀྵྱ་ཏ། །ཏེ་ཏ་
འདི་གསུབ་མི་རུང་།

2019-03-15 14:21 UTC, rekongrabten commented on text/194_སྒྲ་མདོ།_རེ.txt
> +[2b.5]ནུའི་ཏ་པ་ལ་མ་ཡིན་ནོ། །ལིཊ་དང་སྨོས་པའི་ལིང་མ་ཡིན་པའི་ཏིང་ཤ་འགྲོ་བ་ལ་ཡ་ཀའོ། །ཏ་བ་ལས་དཀའ་ཐུབ་ཀྱི་བྱ་བ་ལས་སོ། །བྱེད་པ་པོ་ལ་ཤས་སོ། །ལ་སོགས་པ་ལས་འཇིག་གོ། །ཧུ་རྣམས་ཀྱི་གཉིས་དག་ཀྱང་ངོ་། །ཙཎ་ལས་སོ། །ཡང་
འདི་ཡང་གསུབ་མི་རུང་།

2019-03-15 14:21 UTC, rekongrabten commented on text/194_སྒྲ་མདོ།_རེ.txt
> +[5b.4]ཤ་ལས་སོ། །ཙནྡྲ་པའི་མདོ་ལས་སྐབས་དང་པོའི་རྐང་པ་གསུམ་པ་རྫོགས་སོ།། །།ལའི། ཏིས། ཏས ་ཛྷི། སིབ། ཐས། ཐ། མིས། བས། མས། ཏ། ཨཱ་ཏཱམ། ཛྷ། ཐཱས། ཨཱ་ཐཱཾ། དྷྭམ། ཡིཊ། བ་ཧི། མ་ཧིའོ། །ཨ་ཏ་ལས་ཨཱཏ་ཀྱི་ཨིཏ་དོ། །ཛྷའི་ཨ
འདི་ཡང་གསུབ་མི་རུང་།

2019-03-15 14:21 UTC, rekongrabten commented on text/194_སྒྲ་མདོ།_རེ.txt
> +[5b.5]དོ། །ཛཀྵ་ལ་སོགས་པ་ལྔ་རྣམས་ལས་སོ། །མ་ཡིན་པ་ལས་ཏང་གིའོ། །ཤཱིང་ལས་ར་ཏའོ། །བེ་ཏི་ལས་ཡང་ནའོ། །ལེཊའི་ཨི་ར་ཙའོ། །ཏའི་ཨེ་ཤའོ། །ཏང་མ་ཡིན་པ་རྣམས་ཀྱི་ཎལ། ཨ་ཏུས། ཨུས། ཐལ། ཨ་ཐུས། ཨ། ཎལ། བ་མ་རྣམས་སོ། །བིད་ལས
འདི་ཡང་གསུབ་མི་རུང་།

2019-03-15 14:21 UTC, rekongrabten commented on text/194_སྒྲ་མདོ།_རེ.txt
> +[28b.7]ཤ་ར། ཨིཀྵུ། པླཀྵ། ཨཱམྲ། ཀཱཪྴྱ། པཱིཡཱུཀྵཱ། ཁ་དི་ར་ལས་སོ། །ཨི་རི་ཀཱ་ལ་སོགས་པ་མ་ཡིན་པས་སྨན་གྱི་ཤིང་ལས་ཨཙ་གཉིས་གསུམ་པ་ལས་ཡང་ནའོ། །ལས་ཨ་ཧན་གྱིའོ། །ཏྲི། ཙ་ཏུར་དག་ལས་ཧཱ་ཡན་གྱི་ན་ཚོད་ལའོ། །བ་ཧ་ནམ་གྱི་
འདི་ཡང་གསུབ་མི་རུང་།

2019-03-15 14:21 UTC, rekongrabten commented on text/194_སྒྲ་མདོ།_རེ.txt
> +[36a.1]སྔར་ལྟར་དེ་རྣམས་བསིལ་བར་བྱའོ། །རྀ་ཡིག་ལ་རེ་ཕ་གནས་པ་གང་། དེའི་ནང་ན་གནས་པའམ། དེ་ལ་གལ་ཏེ་དང་པོ་དང་། རེ་ཞིག་དམ་བཅའ་བར་བྱ་སྟེ། ཨགྣིརྲྀཏ་དྷུ་ཤྱ་ཞེས་པ་ནི་གང་ཞིག་རྀ་ཡིག་དང་ལྷན་ཅིག་རེ་པའོ། །དེ་གང་ལས་ཅེ
འདི་ཡང་གསུབ་མི་རུང་།

2019-03-15 14:21 UTC, rekongrabten commented on text/194_སྒྲ་མདོ།_རེ.txt
> +[40a.4]སྨོན་པ་མ་ཡིན་པ་ལ་ཞེས་པ་མདོ་ཕྱི་མ་དག་ལས་གོང་དུའོ། །ཛྷིའི་ཛུསའོ། །ཛུས་ཞེས་པ་ལའོ་ཞེས་པ་ཇི་སྲིད་པར་ཙ་ཏང་ཨཱན་རྣམས་ཅི་ལྟར་ཀླགས་པའོ། །ཏང་ཨཱན་ཞེས་པ་ལུཊ་ལ་ཀླྀཔ་ལས་སོ་ཞེས་པ་ཇི་སྲིད་པར་སྤྱིར་བཏང་བའོ། །ཨཱ
འདི་ཡང་གསུབ་མི་རུང་།

2019-03-15 14:21 UTC, rekongrabten commented on text/194_སྒྲ་མདོ།_རེ.txt
> +[40b.1]ཤས། ཊཱ་བྷྱཱམ་བྷིས། ངེ་བྷྱཱམ་བྷྱཱས། ང་སི་བྷྱཱམ་བྷྱཱས། ངས་ཨོས་ཨཱམ། ངི་ཨོས་སུཔའོ། །འདི་རྣམས་ཀྱང་ཤུགས་ཀྱིས་གཅིག་ལ་སོགས་པ་དང་ལྡན་པའི་དོན་བརྗོད་པའི་སྒྲ་ལས་ཕ་རོལ་དུ་འགྱུར་རོ། །དོན་བརྗོད་པའི་སྒྲ་ལས་ཞེ
འདི་ཡང་གསུབ་མི་རུང་།

2019-03-15 14:21 UTC, rekongrabten commented on text/194_སྒྲ་མདོ།_རེ.txt
> +[40b.1]ཤས། ཊཱ་བྷྱཱམ་བྷིས། ངེ་བྷྱཱམ་བྷྱཱས། ང་སི་བྷྱཱམ་བྷྱཱས། ངས་ཨོས་ཨཱམ། ངི་ཨོས་སུཔའོ། །འདི་རྣམས་ཀྱང་ཤུགས་ཀྱིས་གཅིག་ལ་སོགས་པ་དང་ལྡན་པའི་དོན་བརྗོད་པའི་སྒྲ་ལས་ཕ་རོལ་དུ་འགྱུར་རོ། །དོན་བརྗོད་པའི་སྒྲ་ལས་ཞེ
འདི་ཡང་གསུབ་མི་རུང་།

2019-03-15 14:21 UTC, rekongrabten commented on text/194_སྒྲ་མདོ།_རེ.txt
> +[43b.5]ཞེས་པ་ལས་གོང་དུ་སྤྱིར་བཏང་བའོ། །གཉིས་དག་གི་གཅིག་གོ་ཞེས་པ་རྀཏའི་ཨུཏའོ་ཞེས་པ་ཇི་སྲིད་པར་སྤྱིར་བཏང་བའོ། །ཨ་ལས་ཨེངའོ། །ཨ་ལས་ཞེས་པ་ཨཏའི་ཨེང་ལའོ་ཞེས་པ་ལས་གོང་དུ་སྤྱིར་བཏང་བའོ། །དང་པོའི་ཨ་ཏ་ལས་ཨཱཏ་ཨཻ
འདི་གཉིས་ཆ་གསུབ་མི་རུང་ངོ་།།

2019-03-16 13:12 UTC, rekongrabten requested changes
བསྐྱར་དུ་གཟིགས་རོགས།

2019-03-16 13:12 UTC, rekongrabten commented on text/011_རྒྱུད་འགྲེལ།_ཐ.txt
> +[76a.4]སྦྱར་བ་ལ་ནི་འདི་ཡང་བདག་གིས་ཤེས་རབ་ཡི་གེ་ཨུ་རུ་འགྱུར། །མཾ་མུཿ་ཧཾ་ཧུཿསྃ་སུཿམ་ཉྫུཿ་ཉིད་ནི་པདྨ་ནོར་འདབ་ལ་སྟེ་ཉི་མའི་འདབ་མ་ལ། ༡༩༠ །ཕྱི་རོལ་དུ་ཤྲཱི་བཛྲ་གློཥཿས་དང་ལྡན་པའི་མནྟ་བྷ་དྲ་ཧཱུཾ་དང་ཕཊ་དུ་འགྱུ
འདི་ལ་བསྐྱར་དུ་གཟིགས་རོགས།

2019-03-16 13:12 UTC, rekongrabten commented on text/171_འཁྲི་ཤིང།_ཁེ.txt
> +[19b.1]མེ་ཀ་པཉྩཱ་ཤཿཝཿ།། །།ཨརྠི་ནཱམྦ་ན་ག་ཏོ྅སི་བལྐ་ལཱི་ཡཿཀ་རོ་ཏྱ་བི་ར་ཏཾ་ཀྲྀ་ཏཱརྠ་ཏཱཾ། །ཀཻརྣ་ཙཱ་རུ་ཙ་རི་ཏ་ས་ཙརྩྱ་ཏེ་ཏ་སྱ་ཙིནྟ་ན་ཏ་རོཤྩ་མདྦྷུ་ཏིཿ། །བི་ཧ་རནྟ་མ་
འདི་གསུབ་མི་རུང།

2019-03-16 13:12 UTC, rekongrabten commented on text/194_སྒྲ་མདོ།_རེ.txt
> +[40b.2]བྷིསའི་ཨཻསའོ། །ཨཏ་ས་ཞེས་པ་ཛསཱི་ཤཱིའོ་ཞེས་པ་ཇི་སྲིད་པར་སྤྱིར་བཏང་བའོ། །སཪྺ་ལ་སོགས་པ་རྣམས་ལས་སྨཻ་སྨཱཏ་དག་གོ། །སཪྺ་སོགས་རྣམས་ལས་ཞེས་པ་ཤཱི་ཡང་ནའོ་ཞེས་པ་ཇི་སྲིད་པར་སྤྱིར་བཏང་བའོ། །ཤཱི་ཡང་ནའོ། །ཡང་ན
འདི་ཡང་གསུབ་མི་རུང།

2019-03-19 05:21 UTC, rekongrabten approved these changes

2019-03-19 15:08 UTC, rekongrabten requested changes
འདི་ལ་བསྐྱར་དུ་གཟིགས་རོགས། 2019-3-19

2019-03-19 15:08 UTC, rekongrabten commented on text/157_འདུལ་བ།_ཚུ.txt
> +[151a.7]ཀྱིས་སྨད་པའི་ཕྱིར་རོ། །སྡིག་པ་ཅན་གྱིས་གཞི་ཞེས་བྱ་བ་ནི་དམ་པ་མ་ཡིན་པའི་ཆོས་ཉན་པ་ལ་སོགས་པ་དོན་མེད་པའི་རྒྱུར་གྱུར་པ་ཡིན་པའི་ཕྱིར་རོ། །ཕྲི་ཞེས་བྱ་བ་ནི་གཅད་པའོ། །ཤེས་པ་ཅན་རེམ་ཅིག་ཅེས་བྱ་བ་ནི་བརྡའི་
འདིའི་ཤོག་ངོས་འོག་མ་ཐིག་མགོར་གཟིགས་རོགས།

2019-03-20 14:02 UTC, rekongrabten approved these changes

2019-03-20 14:02 UTC, merged