2019/3/14
Esukhia/derge-tengyur pull request #2
Opened 2019-03-14 11:37 UTC by tashikuncok

2019-03-15 04:14 UTC, tseringwa requested changes
བསྐྱར་བཟོ་བྱེད་རོགས།

2019-03-15 04:14 UTC, tseringwa commented on text/208_སྒྲ་མདོ།_ཏོ.txt
> -[376a.1]དང་སྦྱར་བའི་དཔེར་བརྗོད་ནི། སཾ་ཛྙ་པ་ཡ་ཏི་ཤཱ་ཏྲུན། བིཛྙ་པ་ཡ་ཏི་རཱ་ཛཱ་ནཾ། ཛྙ་པ་ཡ་ཏི་ཤ་སྟྲཾ་ལྟ་བུའོ། ༈ །ཛྭ་ལ་འབར་བ་ལ་ཎི་ཙ་སྦྱར། ཛྭ་ལ་ཧྭ་ལ་ཧྨ་ར་ན་མོ་྅་ནུ་བ་སརྒཱ་ཏ་པཱ་གླཱ་སྤཱ་པ་ཊྭ་མ་ཤྩ། ཉེར་བསྒྱུར་
[376a.1 སྣླ --སྣཱ་ཡིན་པ་འདྲ།

2019-03-15 06:18 UTC, tseringwa approved these changes

2019-03-15 06:20 UTC, tseringwa approved these changes

2019-03-15 06:21 UTC, tseringwa approved these changes

2019-03-15 14:41 UTC, rekongrabten requested changes
འདི་དག་ལ་བསྐྱར་དུ་གཟིགས་རོགས་མཁྱེན།

2019-03-15 14:41 UTC, rekongrabten commented on text/203_སྣ་ཚོགས།_ངོ.txt
> +[15b.6]ཚད་མཆན་ཉིད་ཀྱི། །སྒྲ་དོན་ལེགས་པའི་བསྒྱུར་བ་ཡིན།། ༄། །གྲུབ་ཐོབ་བརྒྱད་བཅུའི་མངོན་པར་རྟོགས་པ་བཞུགས།། {D4317} ༄༅༅། །ཐམས་ཅད་མཁྱེན་པ་ལ་ཕྱག་འཚལ་ལོ། །ལཱུ་ཡི་པ་དུ་བའི་མདོག་ཅན། སྐྱེ་པ་དང་ལྷན་ཅིག་པའོ། །ལ
འདིའི་ཆོས་ཨང་ཆོས་ཚན་གྱི་མཆན་བྱང་གི་མདུན་ལ་འཇོག་རོགས། དེ་ལས་གཞན་བཞུགས་ཞེས་པའི་མཐར་ཉིས་ཤད་མེད།

2019-03-15 14:41 UTC, rekongrabten commented on text/203_སྣ་ཚོགས།_ངོ.txt
> +[18a.2]དྲུག་གི་བར་དུ་གྲུ་ལ་ཕྱིན་ན་འབྱིངས་བ་བསྲུང་སོ། །དབང་ཕྱུག་གིས་བསྟན་པའི་རིན་པོ་ཆེའི་བཅུད་ལེན་གྲུབ་པ་རྫོགས་སོ།། །།ཧ་རི་དྷོ་བར་གྱི་རྣལ་འབྱོར་བ་ཤི་བ་དཱ་ཤ་དང་། ཨུ་རྒྱན་པས་བུ་ཏྲར་བསྒྱུར་བའོ།། ༄། །སྤོས
འདི་ཡང་གོང་མཆན་དང་མཚུངས།

2019-03-15 14:41 UTC, rekongrabten commented on text/203_སྣ་ཚོགས།_ངོ.txt
> +[18b.2]སྦྱར་བའི་མིག་མངས་རིས་ཀྱི་སྦྱོར་བ་ཚིག་ལེའུར་བྱས་པ་སློབ་དཔོན་ཀླུ་སྒྲུབ་ཀྱིས་མཛད་པ་བརྫོགས་སོ།། ༄། །སྤོས་ཀྱི་སྦྱོར་བ་རེའུ་ཆར་བྱས་པའི་ཐབས་བཤད་པ་བཞུགས། {D4320}༄༅༅། །དཀོན་མཆོག་གསུམ་ལ་ཕྱག་འཚལ་ལོ། །སྤོ
འདི་ཡང་གོང་མཆན་དང་མཚུངས།

2019-03-15 14:41 UTC, rekongrabten commented on text/203_སྣ་ཚོགས།_ངོ.txt
> +[92a.1]ཚེའི་གནས་སྐབས་ཀྱི་འབྲས་བུ་གནོད་པ་འབྱུང་བ་ཞེས་བྱ་བའི་ལས་བཞུགས་སོ།། {D323}༄༅།།འཕགས་པ་འཇམ་དཔལ་ལ་ཕྱག་འཚལ་ལོ། །གཟའི་གནོད་པ་སྤང་བའོ། །ཉི་མ་ལ་མེ་ལྟར་མཆོད་པར་བྱའོ། །ཟླ་བ་ལ་ཀླུ་མཆོད་པར་བྱའོ། །མིག་དམར་ལ
འདིའི་ཐིག་མགོ་  ༄། །  འདི་འཇོག་དགོས་པ་དང། ཆོས་ཨང་འདིའི་མདུན་དུ་འཇོག་དགོས། དེ་ལས་གཞན་འཕགས་པ་འཇམ་དཔལ་ལ་ཕྱག་འཚལ་ལོ། ། ཞེས་པའི་ཚིག་མགོའི་དབུ་ཁྱུད་ ༄༅༅ འདི་བཞག་ནས་ཤད་གཉིས་ཀྱི་བར་སྟོང་པ་འཇོག་རོགས།

2019-03-15 14:41 UTC, rekongrabten commented on text/203_སྣ་ཚོགས།_ངོ.txt
> +[92b.2]{D4324}༄༅། །རྒྱ་གར་སྐད་དུ། ཙུཌ་མ་ཎི་ནཱ་མ། བོད་སྐད་དུ། གཙུག་གི་ནོར་བུ་ཞེས་བྱ་བ། །ཐམས་ཅད་མཁྱེན་པ་ལ་ཕྱག་འཚལ་ལོ། །ཀཻ་ལཱ་ས་རིའི་གནས་མཆོག་ཏུ། །བསྟན་བཅོས་དབྱངས་འཆར་ཞེས་བྱ་བ། །གཡུལ་ལས་རྣམ་པར་རྒྱལ་བ་བཤ
འདིའི་དབུ་ཁྱུད་༄༅༅། ། འདི་ཡིན་པས་འདི་འཇོག་རོགས།

2019-03-15 14:41 UTC, rekongrabten commented on text/203_སྣ་ཚོགས།_ངོ.txt
> +[96b.7]བའོ།། {D4325}༄༅། །རྒྱ་གར་སྐད་དུ། ཨཱ་ཡུ་གཎི་ཏ་ཕ་ལ་བྲ་ཀ་ཤ་ནཱ་མ། བོད་སྐད་དུ། ཚེ་རྩིས་ཀྱི་འབྲས་བུ་གསལ་བར་བྱེད་པ་ཞེས་བྱ་བ། འཇམ་པའི་དབྱངས་ལ་ཕྱག་འཚལ་ལོ། །གནས་སྐབས་བཞིན་ཤེས་སྐྱེས་བུ་ཡིས། །དང་པོའི་གནས་
འདིའི་དབུ་ཁྱུད་  ༄༅༅། ། འདི་ཡིན།

2019-03-15 14:41 UTC, rekongrabten commented on text/203_སྣ་ཚོགས།_ངོ.txt
> +[97a.6]འབྲས་ཀྱི་རྩིས་གསལ་པར་བྱེད་བ་མ་ན་པུ་རུ་ཐས་མཛད་པ། །ཨྠི་ནི་ཀ་ར་ཀཊའི་བྲམ་ཟེ་ལག་མ་ཏི་དང་། མཁའ་འགྲོ་རྡོ་རྗེས་བསྒྱུར།། {D4326}༄༅། །རྒྱ་གར་སྐད་དུ། སྭ་རོད་ཡ་ཨ་རཱ་སཾ་གྲ་ཧ། བོད་སྐད་དུ། དབྱངས་འཆར་བའི་དོན་
འདི་ཡང་གོང་དང་མཚུངས།

2019-03-15 14:41 UTC, rekongrabten commented on text/203_སྣ་ཚོགས།_ངོ.txt
> +[99a.1]གཏན་ལ་ཕབ་པའོ།། {D4327}༄༅། །རྒྱ་གར་སྐད་དུ། སྭ་རོ་ད་ཡ་ཀཱ་ལ་ཡུག་ཕ་ལ་ཨུ་བ་དེ་ཤ །བོད་སྐད་དུ། དབྱངས་འཆར་བའི་དུས་སྦྱོར་གྱི་འབྲས་བུ་ཉེ་བར་མཁོ་བ། ཨཱ་རྱ་མ་ཉྫུ་ཤྲི་ཡེ་ན་མཿ། ལུག་གི་དུས་སྦྱོར་ཤར་མ་ཐག་ཏུ། །
འདི་ཡང་གོང་དང་མཚུངས།

2019-03-15 14:41 UTC, rekongrabten commented on text/203_སྣ་ཚོགས།_ངོ.txt
> +[99b.4]{D4328}༄༅། །རྒྱ་གར་སྐད་དུ། བྲ་ཛྙཱ་ཤ་ཏི་ཀ་ནཱ་མ་བྲ་ཀར་ཎ། བོད་སྐད་དུ། ཤེས་རབ་བརྒྱ་བ་ཞེས་བྱ་བའི་རབ་ཏུ་བྱེད་པ། འཇམ་དཔལ་གཞོན་ནུ་གྱུར་བ་ལ་ཕྱག་འཚལ་ལོ། །གང་ཞིག་ལེགས་པར་རྟོགས་པ་ཡིས། །མི་རྣམས་ཤེས་རབ་བརྒྱ
འདི་ཡང་གོང་དང་མཚུངས།

2019-03-15 14:41 UTC, rekongrabten commented on text/203_སྣ་ཚོགས།_ངོ.txt
> +[150b.3]བཅོས་བསྡུས་པ་བཞུགས། །{D4337}༄༅༅། །གང་ལ་གཉེར་མ་ལྔ་ཡོད་ཅིང་། །དེ་ཡི་སྣ་རྒྱུད་མཐོ་བ་དང་། །དཔྲལ་བའི་མཐའ་གཉིས་རྒྱས་ཤིང་མཐོ། །ལུས་པོ་ཤིན་ཏུ་སྦོམ་ལ་སྙོམས། །མགོ་བོ་ཟླུམ་ཞིང་རབ་ཏུ་རྒྱས། །སྨ་ར་སྲབ་ཅིང་
འདིའི་ཆོས་ཨང་ཆོས་ཚན་གྱི་མཚན་བྱང་གི་མདུན་དུ་བཀོད་པ་དང་  བཞུགས། །  ཞེས་པའི་མཐའི་ཤད་གཉིས་དེ་མེད།

2019-03-15 14:41 UTC, rekongrabten commented on text/203_སྣ་ཚོགས།_ངོ.txt
> +[153b.1]འཇིག་རྟེན་དབང་ཕྱུགས་གྲུབ་པ་ཐོབ་པའི་ལོ་རྒྱུས་བཞུགས།། {D4339}༄༅༅། །ན་མོ་ལོ་ཀི་ཤྭ་རཱ་ཡ། སྔོན་རྒྱ་གར་ལྷོ་ཕྱོགས་ན་བསྟན་པ་དར་བའི་ཚེ་གཙུག་ལག་ཁང་ཆེན་པོ་གཅིག་ན་པཎྜི་ཏ་ཏིང་ངེ་འཛིན་ལ་བརྟན་པ་ཐོབ་པ་ཅིག་སྔ
འདི་ཡང་གོང་མཆན་དང་མཚུངས།

2019-03-15 14:41 UTC, rekongrabten commented on text/203_སྣ་ཚོགས།_ངོ.txt
> +[156a.2]བི་ན་ཡ་ཤྲཱིས་བསྒྱུར་རོ།།{D4344}༄༅༅། །ན་མོ་ལོ་ཀེ་ཤྭ་རཱ་ཡ། སྔོན་རྒྱ་གར་ལྷོ་ཕྱོགས་སུ་བསྟན་པ་དར་པའི་ཚེ། གྲོང་ཁྱེར་ཆེན་པོ་ཅིག་ན་ཚོང་དཔོན་གྱི་བུ་སུ་ཁ་དེ་བཞེས་བས་ལོངས་སྤྱོད་ཐམས་ཅད་རང་གིས་ཆུད་གསན་ནས་
ཆོས་ཨང་གི་མདུན་ལ་སྟོང་པ་དགོས།

2019-03-18 15:02 UTC, rekongrabten requested changes
ཁྱེད་ཀྱི་ལས་ཀ་ཁག་བསྐྱར་དུ་བཟོ་རོགས།

2019-03-18 15:02 UTC, rekongrabten commented on text/211_སྣ་ཚོགས།_ནོ.txt
> +[134a.6]ཤས་ལ་སོགས་པ་ཨཙ་དང་པོ་ཅན་ནི། ཨནའི་ཨཏ་དབྱིའོ། །ཞེས་པས་ཨཏ་དབྱིའོ། །བེམྣཿ བེམ་ནཱཿ བམྦྷྱཱཿ བམྦྷི།༄། །སུ་བནྟ་བཞུགས་སོ། ། {D4431}༄༅༅། །རྒྱ་གར་སྐད་དུ། བྱཱ་ཀ་ར་ཎ་སུ་བནྟ་ནཱ་མ། བོད་སྐད་དུ། ལུང་དུ་སྟོན་པ་ས
འདི་མ་དཔེ་གཟིགས་རོགས།

2019-03-18 15:02 UTC, rekongrabten commented on text/211_སྣ་ཚོགས།_ནོ.txt
> +[334b.6]ཚངས་སྲས་བཞད་པའི་རྡོ་རྗེས་དམར་སེར་ཅན་གྱེ་ལོ་ཁྲུམས་ཀྱི་ཟླ་བའི་དཀར་ཆའི་རྒྱལ་བ་དང་པོའི་ཚེས་ལ་རྒྱལ་ཁབ་ཆེན་པོ་པོ་ཏ་ལར་སྦྱར་བའི་ཡི་གེ་པ་ནི་དགེ་སློང་འཇམ་དབྱངས་གྲགས་པས་བགྱིས་པ་ཛ་ཡནྟུ།། །། {D4439}འཕགས་
འདི་ཡང་བསྐྱར་བཟོ་རོགས།

2019-03-18 15:02 UTC, rekongrabten commented on text/211_སྣ་ཚོགས།_ནོ.txt
> +[337a.1](གྲོ་ག་ལ་ཨ་ཋ་གྷནྟས་བྲིས་ཞེས་པ། གུར་གུམ་གླ་རྩི་ག་བུར་གི་ཧཾ་ཙནྡན་དཀར་དམར། ཨ་ཀ་རུ། ཨ་ཀ་ར། གོ་སྟོད་མ་རྣམས་ལ། ཨ་ཋ་གྷནྟས་གཟེར་རོ། །འཁོར་ལོ་གཉིས་བྲིས་གཅིག་མགུལ་དུ་གདགས་གཅིག་ཆུ་ལ་བཀྲུས་ནས་གྲོ་ག་ཕྱིར་
འདི་ག་རེ་ཡིན་ནམ།

2019-03-19 14:59 UTC, rekongrabten requested changes
བསྐྱར་གཟིགས་གནང་རོགས།2019-3-19

2019-03-19 14:59 UTC, rekongrabten commented on text/203_སྣ་ཚོགས།_ངོ.txt
> +[20b.1] {D4321}༄། །ཐུབ་པ་ཆེན་པོ་དྲང་སྲོང་གར་གས་ལྟས་ཀྱི་རྣམ་པ་བསྟན་པ་བཞུགས། ༄༅༅། །ཐུབ་པ་ཆེན་པོ་དྲང་སྲོང་གར་གས་ལྟས་ཀྱི་རྣམ་པ་བསྟན་པ་ཞེས་བྱ་བའི་གཙུག་ལག །ཐམས་ཅད་མཁྱེན་པ་ལ་ཕྱག་འཚལ་ལོ། །གཟའ་སྐར་རིག་པའི་ཕ་ར
འདི་ལ་སྟོང་པ་མི་དགོས།

2019-03-19 14:59 UTC, rekongrabten commented on text/211_སྣ་ཚོགས།_ནོ.txt
> +[2b.6]འདར་བ་ལའོ། །ཀྲོ་ཀྲྀ་ལྟ་བའམ་མཐོང་བ་ལའོ། །ཏོ་ཀྲྀ། ཏྲོ་ཀྲྀ་འགྲོ་བ་ལའོ། །ལོ་ཙྭི་ལྟ་བ་ལའོ། །པྱ་དུ་ཀུ་ན་དུ་དགའ་བའམ་འགྲན་པ་ལའོ། །ཊུ་ཨོ། རྡོ་རྗེ་གྲུ་གུ། སྐདྡྷ་ཐོག་དབབ་པ་ལའོ། །ལུཉྩ་སེལ་བ་ལའོ། །པཉྩུ་སླུ་བ
འདི་ལ་བསྐྱར་དུ་གཟིགས་རོགས།

2019-03-19 14:59 UTC, rekongrabten commented on text/211_སྣ་ཚོགས།_ནོ.txt
> +[141b.7]ཡིག་ནི་ཨཱ་ཏ་ཤཱི་དྱོ་ཞེས་པས་མཚན་མའི་དོན་ཏོ། །ཨཱོཏ་ཨཏ་ཨེ་ཊ་ཞེས་པས་ཨེ་ཉིད་དོ། ༢ །ཛསྴ་སོཿ།། །།༄། །རྐྱེན་གསུམ་བཤད་པ་བཞུགས་སོ།། {D4432}༄༅།  །རྒྱ་གར་སྐད་དུ། ཏྲི་ཎི་བྲ་ཏྱ་ཡ་བྷ་ཥཱཾ། བོད་སྐད་དུ། རྐྱེན་ག
ཆོས་ཨང་མཆན་བྱང་གི་མདུན་ལ་འཇོག་རོགས།

2019-03-19 14:59 UTC, rekongrabten commented on text/211_སྣ་ཚོགས།_ནོ.txt
> +[149b.1] {T4433}༄། །འཇམ་དཔལ་གྱི་བྱཱ་ཀར་ཎའི་རྩ་བ་བཞུགས།། ༄༅༅། །རྒྱ་གར་སྐད་དུ། མཉྫུཤྲླིཤབྡ་ལཀྵ་ཎམ། བོད་སྐད་དུ། འཇམ་དཔལ་གྱི་སྒྲའི་མཚན་ཉིད། གསུང་གི་དབང་ཕྱུག་ལ་ཕྱག་འཚལ་ལོ། །ཨ་ཨི་ཨུཎ། རིལྀཀ །ཨེ་ཨོང་།
འདིའི་མདུན་ལ་སྟོང་པ་མི་དགོས།

2019-03-19 14:59 UTC, rekongrabten commented on text/211_སྣ་ཚོགས།_ནོ.txt
> +[290a.6]རོ། །རྣ་བ་ཕག་ལྟ་བུར་འགྱུར་རོ། །མིག་བྱ་རྒོད་ལྟ་བུར་འགྱུར་རོ། །འདི་ཐམས་ཅད་ཀྱིས་མི་འདྲེགས་པར་འགྱུར་རོ། །འཕགས་པ་རྒྱལ་མ་ཞེས་བྱ་བའི་རིལ་བུ་ཡོངས་སུ་རྫོགས་སོ།། །། {D4436}ན་མོ་ར་ཏྣ་ཏྲ་ཡཱ་ཡ། ན་མ་ཤྩ་ཎྜ་
འདི་ལ་སྟོང་པ་མི་དགོས།

2019-03-19 14:59 UTC, rekongrabten commented on text/211_སྣ་ཚོགས།_ནོ.txt
> +[294a.1]ནད་སེལ་བར་བྱེད་དོ། །བའི་ཆུ་དང་ལྷན་ཅིག་གིས་མེ་དབལ་སེལ་བར་བྱེད་དོ། །འཕགས་པ་རྩ་བའི་མཛོད་སྨན་ཆེན་པོའི་རིམ་པ་སློབ་དཔོན་དཔལ་ལྡན་འཕགས་པ་ཀླུ་[སྒྲུབ]་གྱི་ཞལ་སྔ་ནས་མཛད་པ་རྫོགས་སོ།། །། {D4437}པྲི་ཡཾ་
འདི་ལ་སྟོང་པ་མི་དགོས།

2019-03-19 14:59 UTC, rekongrabten commented on text/211_སྣ་ཚོགས།_ནོ.txt
> +[334b.6]ཚངས་སྲས་བཞད་པའི་རྡོ་རྗེས་དམར་སེར་ཅན་གྱེ་ལོ་ཁྲུམས་ཀྱི་ཟླ་བའི་དཀར་ཆའི་རྒྱལ་བ་དང་པོའི་ཚེས་ལ་རྒྱལ་ཁབ་ཆེན་པོ་པོ་ཏ་ལར་སྦྱར་བའི་ཡི་གེ་པ་ནི་དགེ་སློང་འཇམ་དབྱངས་གྲགས་པས་བགྱིས་པ་ཛ་ཡནྟུ།། །། {D4439}འཕགས་
འདི་ལ་སྟོང་པ་མི་དགོས།

2019-03-19 14:59 UTC, rekongrabten commented on text/211_སྣ་ཚོགས།_ནོ.txt
> +[354a.6]སྟོད་པ་འཇམ་དབྱངས་དབང་པོས་བགྱིས་པ་འདིས་ཀྱང་འགྲོ་བ་མང་པོ་ལ་ཕན་པར་གྱུར་ཅིག །ཤུ་བྷ་མསྟུ་སརྦ་ཛ་ག་ཏཾ།། །། {D4442}འཕགས་ཡུལ་དབུས་འགྱུར་མཐུ་རའི་རྒྱལ་རིགས་ཀྱི་སྨན་བར་གུནཱ་ཐའི་གདམས་པ་བཞུགས་སོ།། །།
འདི་ལ་ཡང་སྟོང་པ་མི་དགོས།

2019-03-19 14:59 UTC, rekongrabten commented on text/211_སྣ་ཚོགས།_ནོ.txt
> +[358b.1]{D4444}འཕྲུལ་གྱི་མེ་ལོང་དགུ་སྐོར་ཞེས་བྱ་བའི་རྩ་འགྲེལ་བཞུགས།  །ཀུན་མཁྱེན་ཉིད་ལ་ཕྱག་འཚལ་ལོ། །རྣལ་འབྱོར་ལྟ་བའི་སྤྱི་འགྲེལ་བརྡེག །ལོག་རྟོག་བྱང་ཆུབ་ཡུལ་སྣང་བའི། །ཆོས་ཀུན་
འདི་ལ་ཡང་གཟིགས་རོགས།

2019-03-19 14:59 UTC, rekongrabten commented on text/211_སྣ་ཚོགས།_ནོ.txt
> +[360b.1]ཆེད་བགྱིས་པའི། །དགེ་རྩས་བདག་དང་མཐའ་ཡས་འགྲོ་བར་བསྔོ། །འཕྲུལ་གྱི་མེ་ལོང་དགུ་སྐོར་རྫོགས་སོ།། །། {D4445}༄། །འགྲེལ་པ་བཞུགས། །༄༅༅། །རྣལ་འབྱོར་རིགས་པའི་མེ་ཏོག་འཕྲུལ་
སྟོང་པ་མི་དགོས།

2019-03-19 14:59 UTC, rekongrabten commented on text/211_སྣ་ཚོགས།_ནོ.txt
> +[368a.2]སྐོར་ལ། རིག་པའི་མེ་ཏོག་གིས་འགྲེལ་པའོ། །སློབ་དཔོན་ཆེན་པོ་བི་མཱ་ལས་མཛད་པ་རྫོགས་སོ།། །།༄། །ཐུགས་ཀྱི་སྒྲོན་མ་བཞུགས། ། {D4446}༄༅༅། །དེ་བཞིན་གཤེགས་པ་ཐམས་ཅད་ཀྱི། །སྐུ་གསུང་ཐུགས་ཀྱི་རྡོ་རྗེའི་
འདིའི་ཆོས་ཨང་ཆོས་མཚན་གྱི་མདུན་ལ་འཇོག་རོགས།

2019-03-19 14:59 UTC, rekongrabten commented on text/211_སྣ་ཚོགས།_ནོ.txt
> +[378b.4]འགྱུར་དབུལ་སེལ་ལྟར། །སྐལ་བ་ཐུགས་ཀྱི་རིན་ཆེན་ནོར། །སྟོན་ཚིག་སྒྲོན་མ་འདི་རྙེད་ཤོག །ཐུགས་ཀྱི་སྒྲོན་མ་དཔལ་དབྱངས་ཀྱིས་མཛད་པ་རྫོགས་སོ།། །། {D4447}༄། །ལྟ་བ་ཡང་དག་སྒྲོན་མ་བཞུགས། །༄༅༅། །དཔལ་ལྡན་ཐུགས་ཀ
སྟོང་པ་མི་དགོས།

2019-03-19 14:59 UTC, rekongrabten commented on text/211_སྣ་ཚོགས།_ནོ.txt
> +[379a.7]གཉིས་པོ་མ་སྐྱེས་ཕྱིར། །རྣམ་པར་རྟོག་པའི་མཚན་མ་ཅི་བྱུང་ཡང༌། །མ་བཀག་རང་བྱུང་མ་འབྲངས་རང་ཞི་སྟེ། །མ་བཅོས་མ་བྱས་རང་གི་ངང་གིས་གསལ། །ལྟ་བ་ཡང་དག་སྒྲོན་མ་རྫོགས་སོ།། །།ཨཱ་ཙརྱ་དཔལ་དབྱངས་ཀྱིས་མཛད་པའོ།། །།
སྟོང་པ་མི་དགོས།

2019-03-19 14:59 UTC, rekongrabten commented on text/211_སྣ་ཚོགས།_ནོ.txt
> +[379b.6]རྟོག་ཟབ་མོའི་ཉམས་མྱོང་བ། །མྱོང་བ་ཡིན་ཕྱིར་དེ་ཉིད་མིན། །ལྟ་བ་དགུམ་ཆུང༌། མཐའི་མུན་སེལ་སྒྲོན་མ། བོད་ཀྱི་པཎྜི་ཏ་ཨཱ་ཙརྱ་གཉན་དཔལ་དབྱངས་ཀྱིས་མཛད་པའོ།། །།༄། ། {D4449}༄༅༅། །ཐབས་ཤེས་སྒྲོན་མ་བཞུགས། །དུས
འདི་ལ་ཡང་བལྟ་རོགས།

2019-03-20 13:56 UTC, rekongrabten requested changes
འདི་དག་ལ་བསྐྱར་དུ་གཟིགས་རོགས། 2019-30-20

2019-03-20 13:56 UTC, rekongrabten commented on text/203_སྣ་ཚོགས།_ངོ.txt
> +[20b.1] {D4321}༄། །ཐུབ་པ་ཆེན་པོ་དྲང་སྲོང་གར་གས་ལྟས་ཀྱི་རྣམ་པ་བསྟན་པ་བཞུགས། ༄༅༅། །ཐུབ་པ་ཆེན་པོ་དྲང་སྲོང་གར་གས་ལྟས་ཀྱི་རྣམ་པ་བསྟན་པ་ཞེས་བྱ་བའི་གཙུག་ལག །ཐམས་ཅད་མཁྱེན་པ་ལ་ཕྱག་འཚལ་ལོ། །གཟའ་སྐར་རིག་པའི་ཕ་ར
འདིའི་མདུན་ལ་སྟོང་པ་མི་དགོས་ལབ་ཀྱི་ཡོད།

2019-03-20 13:56 UTC, rekongrabten commented on text/211_སྣ་ཚོགས།_ནོ.txt
> +[2b.6]འདར་བ་ལའོ། །ཀྲོ་ཀྲྀ་ལྟ་བའམ་མཐོང་བ་ལའོ། །ཏོ་ཀྲྀ། ཏྲོ་ཀྲྀ་འགྲོ་བ་ལའོ། །ལོ་ཙྭི་ལྟ་བ་ལའོ། །པྱ་དུ་ཀུ་ན་དུ་དགའ་བའམ་འགྲན་པ་ལའོ། །ཊུ་ཨོ། རྡོ་རྗེ་གྲུ་གུ། སྐདྡྷ་ཐོག་དབབ་པ་ལའོ། །ལུཉྩ་སེལ་བ་ལའོ། །པཉྩུ་སླུ་བ
འདི་ལ་ཡང་བསྐྱར་དུ་གཟིགས་རོགས།

2019-03-20 13:56 UTC, rekongrabten commented on text/211_སྣ་ཚོགས།_ནོ.txt
> +[290a.6]རོ། །རྣ་བ་ཕག་ལྟ་བུར་འགྱུར་རོ། །མིག་བྱ་རྒོད་ལྟ་བུར་འགྱུར་རོ། །འདི་ཐམས་ཅད་ཀྱིས་མི་འདྲེགས་པར་འགྱུར་རོ། །འཕགས་པ་རྒྱལ་མ་ཞེས་བྱ་བའི་རིལ་བུ་ཡོངས་སུ་རྫོགས་སོ།། །། {D4436}ན་མོ་ར་ཏྣ་ཏྲ་ཡཱ་ཡ། ན་མ་ཤྩ་ཎྜ་
འདི་ལ་སྟོང་པ་མི་དགོས།

2019-03-20 13:56 UTC, rekongrabten commented on text/211_སྣ་ཚོགས།_ནོ.txt
> +[294a.1]ནད་སེལ་བར་བྱེད་དོ། །བའི་ཆུ་དང་ལྷན་ཅིག་གིས་མེ་དབལ་སེལ་བར་བྱེད་དོ། །འཕགས་པ་རྩ་བའི་མཛོད་སྨན་ཆེན་པོའི་རིམ་པ་སློབ་དཔོན་དཔལ་ལྡན་འཕགས་པ་ཀླུ་[སྒྲུབ]་གྱི་ཞལ་སྔ་ནས་མཛད་པ་རྫོགས་སོ།། །། {D4437}པྲི་ཡཾ་
འདི་ལ་ཡང་སྟོང་པ་མི་དགོས།

2019-03-20 13:56 UTC, rekongrabten commented on text/211_སྣ་ཚོགས།_ནོ.txt
> +[379b.6]རྟོག་ཟབ་མོའི་ཉམས་མྱོང་བ། །མྱོང་བ་ཡིན་ཕྱིར་དེ་ཉིད་མིན། །ལྟ་བ་དགུམ་ཆུང༌། མཐའི་མུན་སེལ་སྒྲོན་མ། བོད་ཀྱི་པཎྜི་ཏ་ཨཱ་ཙརྱ་གཉན་དཔལ་དབྱངས་ཀྱིས་མཛད་པའོ།། །།༄། ། {D4449}༄༅༅། །ཐབས་ཤེས་སྒྲོན་མ་བཞུགས། །དུས
ཆོས་ཨང་གི་སྔ་ཕྱི་གཉིས་ལ་དབུ་ཁྱུད་ཡོད་པ་ཅི་ཡིན་ནམ།

2019-03-21 14:07 UTC, rekongrabten requested changes
བསྐྱར་དུ་གཟིགས་རོགས་གནང་རྒྱུ་དང་སྣ་ཚོགས་ནོའི་ནང་གི་ཆོས་ཨང་ཁག་ལ་བསྐྱར་དུ་ཞིབ་འཇུག་གནང་རོགས། 2019-3-21

2019-03-21 14:07 UTC, rekongrabten commented on text/211_སྣ་ཚོགས།_ནོ.txt
> +[122b.3] {D4430}༄། །སུ་པྲའི་མཐའ་རིན་ཆེན་འབྱུང་གནས་ཞེས་བྱ་བ་བཞུགས། ༄༅༅། །རྒྱ་གར་སྐད་དུ། སུ་པདྨཱ་ཀ་ར་ནཱ་མ། བོད་སྐད་དུ། སུ་པའི་མཐའ་རིན་ཆེན་འབྱུང་གནས་ཞེས་བྱ་བ། རྫོགས་པའི་སངས་རྒྱས་ལ་ཕྱག་འཚལ་ལོ། །གང་ཞིག་འཕ
འདིའི་མདུན་ལ་སྟོང་པ་མི་དགོས།

2019-03-21 14:07 UTC, rekongrabten commented on text/211_སྣ་ཚོགས།_ནོ.txt
> +[141b.7]ཡིག་ནི་ཨཱ་ཏ་ཤཱི་དྱོ་ཞེས་པས་མཚན་མའི་དོན་ཏོ། །ཨཱོཏ་ཨཏ་ཨེ་ཊ་ཞེས་པས་ཨེ་ཉིད་དོ། ༢ །ཛསྴ་སོཿ།། །།༄། །རྐྱེན་གསུམ་བཤད་པ་བཞུགས་སོ།། {D4432}༄༅།  །རྒྱ་གར་སྐད་དུ། ཏྲི་ཎི་བྲ་ཏྱ་ཡ་བྷ་ཥཱཾ། བོད་སྐད་དུ། རྐྱེན་ག
ཆོས་ཨང་གི་གནས་ནོར་འདུག

2019-03-23 02:20 UTC, rekongrabten approved these changes

2019-03-23 02:23 UTC, rekongrabten requested changes
འདི་གཅིག་པུ་བཟོ་དགོས་པ་དང། དེ་ལས་སྒྲ་མདོ་ཏོ། =བཙལ་ནས་གཙང་མ་བཟོ་རོགས།

2019-03-23 02:23 UTC, rekongrabten commented on text/211_སྣ་ཚོགས།_ནོ.txt
> +[379b.6]རྟོག་ཟབ་མོའི་ཉམས་མྱོང་བ། །མྱོང་བ་ཡིན་ཕྱིར་དེ་ཉིད་མིན། །ལྟ་བ་དགུམ་ཆུང༌། མཐའི་མུན་སེལ་སྒྲོན་མ། བོད་ཀྱི་པཎྜི་ཏ་ཨཱ་ཙརྱ་གཉན་དཔལ་དབྱངས་ཀྱིས་མཛད་པའོ།། །།༄། །{D4449}ཐབས་ཤེས་སྒྲོན་མ་བཞུགས། །༄༅༅། །དུས་
ཆོས་ཨང་འདི་དབུ་ཁྱུད་ཀྱི་མདུན་ལ་བཀོད་རོགས།

2019-03-25 14:25 UTC, rekongrabten approved these changes

2019-03-26 10:12 UTC, rekongrabten approved these changes

2019-03-26 10:30 UTC, rekongrabten approved these changes

2019-03-26 10:31 UTC, merged

2019-03-26 10:31 UTC, rekongrabten commented
bbbb