ཆོས་ཚན
Esukhia/derge-tengyur pull request #3
Opened 2019-03-15 06:00 UTC by gyamtso59

2019-03-15 06:06 UTC, tseringwa requested changes

2019-03-15 06:06 UTC, tseringwa commented on text/208_སྒྲ་མདོ།_ཏོ.txt
> +[115b.7]ཅུང་ཟད་ལས་གྲོལ། [ཉི་བ་ཀལ་གྲོལ།] རེ་བ་ལས་གྲོལ། །རིང་བ་ལས་གྲོལ། སྡུག་བསྔལ་ལས་གྲོལ། ལོག མིང་མཐའི་ནང་བྱི་འོས། ན་ཕྱིས། རཱཛཔུརུ་ཥཿ། རྒྱལ་པོའི་སྐྱེས་བུ། འགྲེལ་པར། ཀྲྀཏ་སོགས་ཀྱི་རྐྱེན་མཐའ་ཅན་དང་སྦྱོར
[115b.7]

2019-03-15 06:09 UTC, tseringwa approved these changes

2019-03-15 13:44 UTC, rekongrabten requested changes
འདི་དག་ལ་བསྐྱར་དུ་གཟིགས་རོགས།

2019-03-15 13:44 UTC, rekongrabten commented on text/048_རྒྱུད་འགྲེལ།_ཙི.txt
> +[76b.3]ཐབས་ཀྱི་མགོན་བྱས་ལ། །དེ་ཡི་བསོད་ནམས་ཁྱད་པར་གྱིས། །སེམས་ཅན་གནས་ཆེན་ཐོབ་པར་ཤོག །དཔལ་ཨུ་རྒྱན་གྱི་ཡུལ་ནས་བྱུང་བ་གྲུབ་པའི་འཁོར་ལོ་ཇི་ལྟར་རྙེད་པ་ཀླུའི་བྱང་ཆུབ་ཀྱིས་མཛད་པ་རྫོགས་སོ། །{D2017}༄༅༅། །རྒྱ་
འདིའི་ཤད་གཉིས་ཀྱི་བར་དུ་སྟོང་པ་མེད།

2019-03-15 13:44 UTC, rekongrabten commented on text/048_རྒྱུད་འགྲེལ།_ཙི.txt
> +[80b.4]པོའི་སྒྲུབ་པའི་ཐབས་སློབ་དཔོན་ཤྲཱི་བི་རཱུ་པས་མཛད་པ་རྫོགས་སོ།། །།རྒྱ་གར་ཤར་ཕྱོགས་ཀྱི་པཎྜི་ཏ་དཱ་ན་ཤཱི་ལས་རང་འགྱུར་དུ་མཛད་པའོ།།{D2019}༄༅༅། །འོད་གསལ་འཆར་བའི་རིམ་པ། དཔལ་གཤིན་རྗེ་གཤེད་དམར་པོ་
ཆོས་ཨང་དང་ཤད་གཉིས་ཀྱི་བར་དུ་སྟོང་པ་ཡོད་དགོས།

2019-03-15 13:44 UTC, rekongrabten commented on text/048_རྒྱུད་འགྲེལ།_ཙི.txt
> +[84b.7]བ་དགེ་སློང་ཆོས་རྗེ་དཔལ་གྱིས་བསྒྱུར་ཅིང་ཞུས་ཏེ་གཏན་ལ་ཕབ་པའོ།། །།{D2022}༄༅༅། །རྒྱ་གར་སྐད་དུ། ཡ་མཱ་རི་ཡནྟྲ་ཨ་བ་ལི། བོད་སྐད་དུ། གཤིན་རྗེ་གཤེད་ཀྱི་འཁྲུལ་འཁོར་གྱི་ཕྲེང་བ། བཅོམ་ལྡན་འདས་གཤིན་རྗེ་གཤེད་
མཚམས་འདི་ལ་བལྟས་ན་ཐིག་ཕྲེང་འབེབས་གཅིག་ནོར་འདུག་པས་ཞིབ་གཟིགས་གནང་རོགས།

2019-03-15 13:44 UTC, rekongrabten commented on text/048_རྒྱུད་འགྲེལ།_ཙི.txt
> +[120b.4]རྒྱ་གར་གྱི་མཁན་པོ་བླ་མ་རྗེ་བཙུན་ཆེན་པོ་ཉི་མའི་དབང་པོའི་འོད་ཟེར་གྱི་ཞལ་སྔ་ནས་ཚག་ལོ་ཙཱ་བ་དགེ་སློང་ཆོས་རྗེ་དཔལ་གྱིས་བསྒྱུར་ཅིང་ཞུས་ཏེ་གཏན་ལ་ཕབ་པའོ། །{D2032}༄༅༅། །རྒྱ་གར་སྐད་དུ། ཨུ་པ་དེ་ཤ་སྭ་ཨ་དྷི
འདིའི་མཐའི་ཤད་གཉིས་ཀྱི་བར་གྱི་སྟོང་པ་མེད།

2019-03-16 12:53 UTC, rekongrabten requested changes
ཡང་གཟིགས་རོགས།

2019-03-16 12:53 UTC, rekongrabten commented on text/048_རྒྱུད་འགྲེལ།_ཙི.txt
> +[76b.3]ཐབས་ཀྱི་མགོན་བྱས་ལ། །དེ་ཡི་བསོད་ནམས་ཁྱད་པར་གྱིས། །སེམས་ཅན་གནས་ཆེན་ཐོབ་པར་ཤོག །དཔལ་ཨུ་རྒྱན་གྱི་ཡུལ་ནས་བྱུང་བ་གྲུབ་པའི་འཁོར་ལོ་ཇི་ལྟར་རྙེད་པ་ཀླུའི་བྱང་ཆུབ་ཀྱིས་མཛད་པ་རྫོགས་སོ། །{D2017}༄༅༅། །རྒྱ་
ཆོས་ཨང་གི་མདུན་དུ་སྟོང་པ་བཞག་ནས་ཤད་གཉིས་མཉམ་དུ་སྦྲེལ་རོགས།

2019-03-16 12:53 UTC, rekongrabten commented on text/048_རྒྱུད་འགྲེལ།_ཙི.txt
> +[80b.4]པོའི་སྒྲུབ་པའི་ཐབས་སློབ་དཔོན་ཤྲཱི་བི་རཱུ་པས་མཛད་པ་རྫོགས་སོ།། །།རྒྱ་གར་ཤར་ཕྱོགས་ཀྱི་པཎྜི་ཏ་དཱ་ན་ཤཱི་ལས་རང་འགྱུར་དུ་མཛད་པའོ།།{D2019}༄༅༅། །འོད་གསལ་འཆར་བའི་རིམ་པ། དཔལ་གཤིན་རྗེ་གཤེད་དམར་པོ་
ཆོས་ཨང་གི་མདུན་དུ་སྟོང་པ་ཡོད་དགོས།

2019-03-16 12:53 UTC, rekongrabten commented on text/048_རྒྱུད་འགྲེལ།_ཙི.txt
> +[120b.4]རྒྱ་གར་གྱི་མཁན་པོ་བླ་མ་རྗེ་བཙུན་ཆེན་པོ་ཉི་མའི་དབང་པོའི་འོད་ཟེར་གྱི་ཞལ་སྔ་ནས་ཚག་ལོ་ཙཱ་བ་དགེ་སློང་ཆོས་རྗེ་དཔལ་གྱིས་བསྒྱུར་ཅིང་ཞུས་ཏེ་གཏན་ལ་ཕབ་པའོ། །{D2032}༄༅༅། །རྒྱ་གར་སྐད་དུ། ཨུ་པ་དེ་ཤ་སྭ་ཨ་དྷི
འདིའི་ཤད་གཉིས་གཤིབ་སྟེ་སྟོང་པ་འཇོག་རོགས།

2019-03-18 14:57 UTC, rekongrabten requested changes
བསྐྱར་དུ་གཟིགས་རོགས། 2019-3-18

2019-03-18 14:57 UTC, rekongrabten commented on text/048_རྒྱུད་འགྲེལ།_ཙི.txt
> +[80b.4]པོའི་སྒྲུབ་པའི་ཐབས་སློབ་དཔོན་ཤྲཱི་བི་རཱུ་པས་མཛད་པ་རྫོགས་སོ།། །།རྒྱ་གར་ཤར་ཕྱོགས་ཀྱི་པཎྜི་ཏ་དཱ་ན་ཤཱི་ལས་རང་འགྱུར་དུ་མཛད་པའོ།།{D2019}༄༅༅། །འོད་གསལ་འཆར་བའི་རིམ་པ། དཔལ་གཤིན་རྗེ་གཤེད་དམར་པོ་
འདི་བསྐྱར་དུ་བཟོ་རོགས། ཤད་གཉིས་ཀྱི་རྗེས་སུ་སྟོང་པ་དགོས།

2019-03-18 14:57 UTC, rekongrabten commented on text/048_རྒྱུད་འགྲེལ།_ཙི.txt
> +[120b.4]རྒྱ་གར་གྱི་མཁན་པོ་བླ་མ་རྗེ་བཙུན་ཆེན་པོ་ཉི་མའི་དབང་པོའི་འོད་ཟེར་གྱི་ཞལ་སྔ་ནས་ཚག་ལོ་ཙཱ་བ་དགེ་སློང་ཆོས་རྗེ་དཔལ་གྱིས་བསྒྱུར་ཅིང་ཞུས་ཏེ་གཏན་ལ་ཕབ་པའོ། །{D2032}༄༅༅། །རྒྱ་གར་སྐད་དུ། ཨུ་པ་དེ་ཤ་སྭ་ཨ་དྷི
འདིའི་མ་དཔེ་ལ་གཟིགས་རོགས།

2019-03-18 14:57 UTC, rekongrabten commented on text/202_གསོ་རིག_གོ.txt
> +[167a.4]བླུགས། །གཟེར་འཇོམས་པ་ཡི་མཆོག་ཡིན་ནོ། །ཞེས་བྱ་བ་ལ། སེང་ཕྲོམ་ཇི་སྐད་སྨོས་པའི་སྦྱོར་བས་ཐིགས་པ་མིག་ཏུ་བླུགས་ན། མིག་ནད་ཀྱི་གཟིར་འཇོམས་པར་བྱེད་པའི་དམ་པ་ཡིན་ནོ། །སྐྱེར་པ་པྲ་པུཎྜ་རཱི་ཀ །བསྐོལ་བའི་ཐིག
མ་དཔེར་གཟིགས་རོགས།

2019-03-19 05:03 UTC, rekongrabten requested changes
འདི་དག་ལ་གཟིགས་རོགས།

2019-03-19 05:03 UTC, rekongrabten commented on text/048_རྒྱུད་འགྲེལ།_ཙི.txt
> +[135b.2]ན་ཉི་ཟླ་ལྟར་གྱུར་ཅིག།{D2036}༄༅༅། །རྒྱ་གར་སྐད་དུ། རཀྟ་ཡ་མཱནྟ་ཀ་ནིཥྤ་ན་ན་ཡོ་ནཱ་མ། བོད་སྐད་དུ། གཤིན་རྗེ་གཤེད་དམར་པོའི་རྫོགས་པའི་རྣལ་འབྱོར་ཞེས་བྱ་བ། བཅོམ་ལྡན་འདས་གཤིན་རྗེ་གཤེད་དམར་པོ་ལ་ཕྱག་འཚལ་ལོ
འདི་ལ་བསྐྱར་

2019-03-19 05:03 UTC, rekongrabten commented on text/048_རྒྱུད་འགྲེལ།_ཙི.txt
> +[136b.6]པར་མི་འགྱུར་བཞིན། །གཤིན་རྗེ་གཤེད་དམར་པོའི་རྫོགས་པའི་རྣལ་འབྱོར་ཞེས་བྱ་བ། མཁས་པ་ཆེན་པོ་འཇིགས་མེད་འབྱུང་གནས་སྦས་པས་མཛད་པ་རྫོགས་སོ།།{D2037}༄༅༅། །རྒྱ་གར་སྐད་དུ། ཤྲཱི་རཀྟ་ཡ་མཱ་རི་ཛཱི་བཾ་ཏཏྟྭ་ཨུ་པ་ད
བསྐྱར་དུ་གཟིགས།

2019-03-19 05:03 UTC, rekongrabten commented on text/048_རྒྱུད་འགྲེལ།_ཙི.txt
> +[138b.6]རྒྱ་གར་གྱིས་ཎྜི་ཏ་དངོས་གྲུབ་བརྙེས་པ་དརྤཎ་ཨཱ་ཙཱཪྱ་དེ་ཉིད་དང༌། གློ་བོ་ལོ་ཙཱ་བ་དགེ་སློང་ཤེས་རབ་རིན་ཆེན་གྱིས། ཆོས་ཀྱི་རྒྱལ་པོའི་སྐུ་མཁར་ཉི་ཟུངས་སུ་བསྒྱུར་ཅིང་ཞུས་ཏེ་གཏན་ལ་ཕབ་པའོ།།{D2038}༄༅༅། །རྒྱ
བསྐྱར་དུ་གཟིགས

2019-03-19 05:03 UTC, rekongrabten commented on text/048_རྒྱུད་འགྲེལ།_ཙི.txt
> +[140a.5]ཤར་ཕྱོགས་ཀྱི་པཎྜི་ཏ་དརྦཎ་ཨཱ་ཙཱརྱ་དང་ལོ་ཙཱ་བ་དགེ་སློང་རྡོ་རྗེ་འཛིན་པ་ཞེ་སྡང་རྡོ་རྗེས་བསྒྱུར་ཅིང་ཞུས་ཏེ་སླར་དག་པར་བྱས་སོ། །སྔ་འགྱུར་ལ་འདི་བས་ཚན་ཆེ་ཙམ་གདའོ་གསུང་ངོ༌།།{D2040}༄༅༅། །རྒྱ་གར་སྐད་དུ།
བསྐྱར་དུ་གཟིགས་རོགས།

2019-03-19 05:03 UTC, rekongrabten commented on text/048_རྒྱུད་འགྲེལ།_ཙི.txt
> +[140b.7]གྱི་མན་ངག་ཏིང་ངེ་འཛིན་ལ་མངའ་བརྙེས་པ་དཔལ་འཛིན་གྱིས་མཛད་པ་རྫོགས་སོ།། །།ལོ་པཎ་སྔ་མ་དང་འདྲ། འདིའི་མན་ངག་གཅིག་སྔར་ཡང་སྙན་བརྒྱུད་དུ་བྱུང་འདུག་སྟེ། གཞུང་སྔར་མ་འགྱུར་གསུང༌།།{D2041}༄༅༅། །རང་གི་སེམས་གོ
བསྐྱར་དུ་གཟིགས་རོགས།

2019-03-19 14:48 UTC, rekongrabten requested changes
འདི་དག་ལ་ནན་ཏན་གྱིས་གཟིགས་རོགས། 2019-3-19

2019-03-19 14:48 UTC, rekongrabten commented on text/048_རྒྱུད་འགྲེལ།_ཙི.txt
> +[84a.5]ཞུས་ཏེ་གཏན་ལ་ཕབ་པའོ།།{D2021}༄༅༅། །རྒྱ་གར་སྐད་དུ། རཀྟ་ཡ་མཱ་རི་སཱ་དྷ་ན་བི་དྷི། བོད་སྐད་དུ། གཤིན་རྗེ་གཤེད་དམར་པོའི་སྒྲུབ་ཐབས་ཀྱི་ཆོ་ག །དཔལ་གཤིན་རྗེ་གཤེད་དམར་པོ་ལ་ཕྱག་འཚལ་ལོ། །ཨོཾ་ཧྲཱིཿཥྚྲྀཿཝི་ཀྲྀ་ཏ
འདི་ལ་གཟིགས་རོགས།

2019-03-19 14:48 UTC, rekongrabten commented on text/202_གསོ་རིག_གོ.txt
> +[64b.4]བྱིད་ཆ་གཉིས་ཁ་ར་ཆ་གསུམ་པར་སྦྱར་ལ་དེ་ཐམས་ཅད་སྦྲང་རྩི་དང་ལྷན་ཅིག་རི་ལུར་བྱས་ན། གཅིན་སྲི་བའི་ནད་ལ་སོགས་པ་སྦྱོང་བར་བྱེད་ཅིང་བསྔགས་པ་ཡིན་ནོ། །དུར་བྱེད་དུག་མོ་ཡུངས་ས་བོན། །པི་པི་ལིང་དང་བཅའ་སྒ་རྣམས།
འདི་ལ་ཡང་ཚེག་ཆད་པ་འདྲ།

2019-03-19 14:48 UTC, rekongrabten commented on text/202_གསོ་རིག_གོ.txt
> +[76a.7]བྱ་སྟེ། དེས་ཀྱང་གཞང་གི་ནད་ལ་སོགས་པ་སེལ་བར་བྱེད་དོ། །དེ་བསྐོལ་ཤུ་དག་ཤུ་ཏི་དང་། །ཤིང་ཀུན་རྒྱམ་ཚ་ཐང་ཤིང་དང་། །ར་སྣ་སྦྲང་རྩི་སྦྱར་བ་ཡི། །འཇམ་རྩིས་ནད་སེལ་ཞེས་བྱ་དགེ །ཞེས་བྱ་བ་ལ། ཨེ་རཎྜའི་རྩ་བ་དེ་བས
འདི་ལ་ཡང་གཟིགས་རོགས།

2019-03-19 14:48 UTC, rekongrabten commented on text/202_གསོ་རིག_གོ.txt
> +[104a.7]ཞུམ་ཞིང་མདོག་མི་སྡུག །བཤང་བ་ཁ་དོག་སྣ་ཚོགས་དང་། །ལྟོ་བར་རྩ་ཡི་མདུད་པ་ཆགས། །ངུ་ཞིང་བྱ་རྒོད་དྲི་ལྡན་ལ། །ཡུན་རིངས་ན་བར་བྱེད་པ་ཡིན། །ཞེས་བྱ་བ་ལ། ནམ་གྲུ་སྐེམ་མོ་ཞེས་བྱ་བའི་གདོན་གྱི་རྟགས་ནི། །ལུས་ཀྱ
འདི་ཡང་གཟིགས་རོགས།

2019-03-19 14:48 UTC, rekongrabten commented on text/202_གསོ་རིག_གོ.txt
> +[153a.6]རབ་རིབ་ལ། །འཚོ་བྱེད་འབྲས་བུ་གསུམ་དང་ནི། །བསྐོལ་བའི་མར་ནི་བླུད་བྱ་ཞིང་། །སྣུམ་གྱིས་ཞེན་པར་གཏར་ག་གདབ། །ཅེས་བྱ་བ་ལ། མཁྲིས་པ་ལས་གྱུར་པའི་རབ་རིབ་གྱི་མིག་ནད་ལ་ནི་འཚོ་བྱེད་ཀྱི་སྡེ་ཚན་དང་། །འབྲས་བུ་ག
འདི་ལ་ཡང་གཟིགས་རོགས།

2019-03-19 14:48 UTC, rekongrabten commented on text/202_གསོ་རིག_གོ.txt
> +[198b.7]རླུང་ལས་གྱུར་པའི་ཁ་ཤུལ་ནི་པི་པི་ལིང་ལ་སོགས་པའི་ཕྱི་མས་གདབ་པའམ། འདེ་གུས་བསྐུ་བར་བྱའོ། །ཡང་ན་རླུང་འཇོམས་སྨན་བསྐོལ་བའི། །ཏིལ་མར་སྣ་སྨན་མཁུར་བཀང་ཕན། །ཞེས་བྱ་བ་ལ། ཡང་རླུང་ལས་གྱུར་བའི་ཁ་ཤུལ་རླུང་སེ
འདི་ཡང་གཟིགས་རོགས།

2019-03-19 14:48 UTC, rekongrabten commented on text/202_གསོ་རིག_གོ.txt
> +[205a.7]བསྐོལ་བ་ཡི། །འོ་མ་ལུས་བ་དེ་བསྒྲངས་ལ། །བསྲུབས་ཏེ་སྙིང་བོ་བླངས་ནས་ནི། །དེ་ནས་མངར་བའི་སྡེ་ཚན་བསྐོལ། །མར་གྱི་སྣ་སྨན་བླུགས་པ་བསྔགས། །ཞེས་བྱ་བ་ལ། བ་ར་ན་ལ་སོགས་པའི་སྡེ་ཚན་གཏུན་གྱི་ནང་དུ་བརྡུངས་པ་འོ་
གཟིགས་རོགས།

2019-03-19 14:48 UTC, rekongrabten commented on text/202_གསོ་རིག_གོ.txt
> +[211a.7]ཞེས་བྱ་བ་ལ། རྨ་མ་རེག་ཅིང་སྐྱོན་མེད་པའི་མཚན་མ་ནི་ལྕེའི་མདོག་འདྲ་བར་སྣང་པ་དང་། རེག་ན་འཇམ་པ་དང་། མཉེན་ཞིང་གྱོང་བག་མེད་པ་དང་། རྨ་ཁ་ཅུང་ཟད་སྨུག་པ་དང་། ཕྱི་རོལ་ན་འབྲུམ་ཕྲན་ཡོད་པ་དང་། དབྱིབས་མཐོ་དམན
གཟིགས་རོགས།

2019-03-19 14:48 UTC, rekongrabten commented on text/203_སྣ་ཚོགས།_ངོ.txt
> +[15b.1]གལ་ཏེ་ལིང་ག་དང་། །ལྷ་མོ་མ་མོའི་ཚོགས་དེ་བཞིན། །གོ་ཆའི་ལས་ནི་བལྟ་བྱས་ནས། །མྱུར་དུ་དེ་རྣམས་གཤེགས་པར་བྱ། །མེ་ཏོག་མཆོད་ཡོན་དེ་བཞིན་དུ། །སྤོས་དང་ཞལ་ཟས་གཏོར་མ་དང་། །གོས་ལ་སོགས་པ་དངུལ་བྱ་ཞིང་། །དེ་བཞི
འདི་ལ་གཟིགས་རོགས།

2019-03-19 14:48 UTC, rekongrabten commented on text/203_སྣ་ཚོགས།_ངོ.txt
> +[38b.7]ཟླར་བ་ལས་གཡོས་ན་འབྲས་བུ་ཟླ་བ་གཉིས་ན་འབྱུང་ངོ་། །དགུན་ཟླ་འབྲིང་པོ་ལས་གཡོས་ན་འབྲས་བུ་ཞག་ལྔ་བཅུ་རྩ་ལྔ་ན་འབྱུང་ངོ་། དགུན་ཟླ་ཐ་ཆུངས་ལས་གཡོས་ན་འབྲས་བུ་ཞག་བརྒྱད་ན་འབྱུང་ངོ་། །དཔྱིད་ཟླ་བ་ལས་གཡོས་ན་འབྲ
འདི་ཡང་ཚེག་ཆད་འདུག

2019-03-19 14:48 UTC, rekongrabten commented on text/203_སྣ་ཚོགས།_ངོ.txt
> +[143a.6]གཡུལ་ལས་རྟག་པར་རྒྱལ་བ་ན། །རྒྱལ་པོའི་བུ་ཞེས་རབ་ཏུ་གྲགས། །ཇི་ལྟར་ཁྱི་ཞིག་བཀྲེས་ཉེན་ཏེ། །རུས་པ་སྐམ་པོ་ཁར་བཅངས་ནས། །ཁྲག་བྱུང་སྡུག་བསྔལ་བདེ་སྙམ་པ། །དེ་བཞིན་འདོད་རྨོངས་རྣམས་ཀྱིས་ནི། །བུད་མེད་རྣམས་ལ
འདི་ལ་གཟིགས་རོགས།

2019-03-19 14:48 UTC, rekongrabten commented on text/208_སྒྲ་མདོ།_ཏོ.txt
> +[37a.7]སྟེ་ཡང་ན་མ་ཡིན་ནོ་ཞེས་པ ཀེག་དང་འདྲ་སྟེ། བཱཀ྄་ག་དང་འདྲ་སྟེ། བཱ་ཀྲ་ ཏ་རི་ཞེས་པ་ལ། བཱ་གྒཱ་རི༔། འཕྲོག་ཁྱོད་དག། བཱ་གྟ་རི༔། དེ་བཞིན་དུ། ཨ་ཙ་ ཧ་ལཽ་ཞེས་པ་ལ། ཨ་ཛྫྷ་ལཽ། དབྱངས་གསལ་དག་ ཨ་ཛྷ་ལཽ། ཥཊ ཧ་ལཱ་ནི
ཁ་རི་ཙ༔   འདི་ལ་ཡང་གཟིགས་རོགས།

2019-03-19 14:48 UTC, rekongrabten commented on text/208_སྒྲ་མདོ།_ཏོ.txt
> +[46b.4]དབྱིའོ། །རྟགས་བྷའི་མིང་ཅན་གྱི་པཱུ་ཥ་ན་ཞེས་པ་ལྟ་བུའི་ཕ་རོལ་དུ་ཤས་སོགས་ཐམས་ཅད་གནས་པའི་མིང་ཅན་མ་ཡིན་པ་ཨ་ཙ་ཐོག་མ་ཅན་ཕ་རོལ་རྟགས་མཐའ་ན་སྲོག་མེད་ཀྱི་སྔ་མའི་ཨ་དེ་དབྱིའོ། །པཱུ་ཥ་ན་ལ། ཤས་ཨ་ཕྱིས། ར་ཥ་སོག
འདི་ལ་བསྐྱར་དུ་གཟིགས་རོགས།

2019-03-19 14:48 UTC, rekongrabten commented on text/208_སྒྲ་མདོ།_ཏོ.txt
> +[124b.6]བྲཧྨཱ། ཏ་ཏྲོ་པ་པ་དཾ་སཔྟ་མཱི་སྠཾ། དེ་ལ་བདུན་པ་གནས་པ་ལ་ཉེ་བའི་ཚིག་གོ། །བསྡུ་བའི་བཞི་ རང་ལུ་ལས་ཚར་ལ་པ། ཚིག་གཉིས་བསྒྲིགས་པའི་སྔ་མ་རྣམ་དབྱེ་བདུན་པ་གནས་བདེ་ལ་ཉེ་བའི་ཚིག་ཅེས་མིང་འདོགས་བྱེད་དོ། །ཨུ་པ
འདི   ཆེན་པོ། ཡིན་པས་དེ་ལྟར་བཟོ་རོགས།

2019-03-19 14:48 UTC, rekongrabten commented on text/208_སྒྲ་མདོ།_ཏོ.txt
> +[244b.7]པས་པ་ཎཱ་ཡ་ཏི་སོགས་ཀྱང་འབྱུང་ངོ་། །ཀ་མེ་རྞིང་། ཀ་མི་ལས་ཎི་ངའོ། །ཀམུ་མཛེས་པ་ལའ་ཞེས་པ་ལ་ངོ་པོའི་རྐྱེན་ཨི་སྦྱར་བའི་ཀ་མི་ལས་ཕ་རོལ་ཏུ་ཎིང་འགྱུར་ཏེ། པཨཏྨ་ནེ་པད་འཇུག་པའི་དོན་དང་། ཎ་བྱིངས་ལ་འཕེལ་བའི་ད
འདི་ལ་ཚེག་དགོས་མོད། མ་དཔེ་མེད་ན་རྟགས་བཀོད་རོགས།

2019-03-20 13:50 UTC, rekongrabten requested changes
ཡང་བསྐྱར་དུ་གཟིགས་རོགས། 2019-3-20

2019-03-20 13:50 UTC, rekongrabten commented on text/202_གསོ་རིག_གོ.txt
> +[9b.2]སྐྲན་གཞང་འབྲུམ། །སྲིན་ནད་གཅིན་སྙི་དམུ་རྫིང་འཇོམས། །ཞེས་བྱ་བ་ལ། རོ་ཧི་ཏ་ཞེས་བྱ་བའི་ལྕུག་མ་མཚོན་གྱིས་དུམ་བུ་དུམ་བུར་གཏུབས་ལ། དུམ་བུ་དེ་དང་ཨ་རུ་རའམ་བ་གཅིན་གྱི་ནང་དུ་ཞག་བདུན་གྱི་བར་དུ་ལེགས་པར་སྦངས་
འདིའི་ཚིག་མཐར་ཚེག་དགོས།

2019-03-20 13:50 UTC, rekongrabten commented on text/202_གསོ་རིག_གོ.txt
> +[104a.7]ཞུམ་ཞིང་མདོག་མི་སྡུག །བཤང་བ་ཁ་དོག་སྣ་ཚོགས་དང་། །ལྟོ་བར་རྩ་ཡི་མདུད་པ་ཆགས། །ངུ་ཞིང་བྱ་རྒོད་དྲི་ལྡན་ལ། །ཡུན་རིངས་ན་བར་བྱེད་པ་ཡིན། །ཞེས་བྱ་བ་ལ། ནམ་གྲུ་སྐེམ་མོ་ཞེས་བྱ་བའི་གདོན་གྱི་རྟགས་ནི། །ལུས་ཀྱ
འདི་ལ་ཡང་ཚེག་དགོས

2019-03-20 13:50 UTC, rekongrabten commented on text/202_གསོ་རིག_གོ.txt
> +[205a.7]བསྐོལ་བ་ཡི། །འོ་མ་ལུས་བ་དེ་བསྒྲངས་ལ། །བསྲུབས་ཏེ་སྙིང་བོ་བླངས་ནས་ནི། །དེ་ནས་མངར་བའི་སྡེ་ཚན་བསྐོལ། །མར་གྱི་སྣ་སྨན་བླུགས་པ་བསྔགས། །ཞེས་བྱ་བ་ལ། བ་ར་ན་ལ་སོགས་པའི་སྡེ་ཚན་གཏུན་གྱི་ནང་དུ་བརྡུངས་པ་འོ་
འདི་ལ་ཡང་ཚེག་དགོས།

2019-03-20 13:50 UTC, rekongrabten commented on text/202_གསོ་རིག_གོ.txt
> +[250a.7]རྒུན་འབྲུམ་ལ་སོགས་པའི་སྨན་གྱི་སྦྱོར་བ་ཇི་སྐད་བཤད་པའི་སྨན་མར་བླུད་ན་ཡང་མངལ་གྱི་རླུང་ནད་སེལ་བ་ལ་སོགས་པའི་ཡོན་ཏན་དང་ལྡན་པ་ཡིན་ནོ། །ཟི་ར་གོ་སྙིད་པི་པི་ལིང་། །ཤུ་དག་རྒྱམ་ཚ་བ་ཤ་ཀ། །ནས་ཚིག་འཁུས་ཐལ་ཏ
ཚེག་གང་ལ་བུད་སོང།

2019-03-21 13:51 UTC, rekongrabten requested changes
འདི་དག་བཟོ་རོགས།2019-3-21

2019-03-21 13:51 UTC, rekongrabten commented on text/067_རྒྱུད་འགྲེལ།_ཆུ.txt
> +[186b.4]དེ་བ་ཏཱ་ནཾ་ར་ས་པཱུ་ཛ་མེ་གྷ་ནི་རྱཏ་ཡཱ་མི་ཧཱུཾ། ཞེས་པས་མཆོད་པར་བྱ་བ་ཉིད་དང་། གཞན་དུ་རེག་བྱ་ཡིད་དུ་འོང་བ་བདག་ཉམས་སུ་མྱོང་བ་ན་བདག་ཉིད་རྣལ་འབྱོར་དང་ལྡན་པ་ལས། རེག་བྱའི་མཆོད་པ་བླ་ན་མེད་པ་སྤྲོས་ཏེ། ཨ
འདི་ལ་བསྐྱར་དུ་གཟིགས་རོགས།

2019-03-21 13:51 UTC, rekongrabten commented on text/202_གསོ་རིག_གོ.txt
> +[6a.7]མེ་དྲོད་སྐྱེད། །རྟུག་འགགས་གྱུར་ནས་སླར་སྣུམ་དང་། །དུགས་བྱས་དེ་འོག་མས་གཏོང་བྱ། །རྩུབ་ཅིང་མས་གཏོང་སྨན་བཅས་པའི། །རྩ་བ་བཅུ་པའི་མས་གཏོང་སྦྱར། །ཞེས་བྱ་བ་ལ། དེའི་འོག་ཏུ་དམུ་རྫིང་ཅན་གྱི་ནད་པ་དེ་ལ་སྲན་ཁུ
ཚེག་དགོས་ཡ

2019-03-21 13:51 UTC, rekongrabten commented on text/202_གསོ་རིག_གོ.txt
> +[9b.2]སྐྲན་གཞང་འབྲུམ། །སྲིན་ནད་གཅིན་སྙི་དམུ་རྫིང་འཇོམས། །ཞེས་བྱ་བ་ལ། རོ་ཧི་ཏ་ཞེས་བྱ་བའི་ལྕུག་མ་མཚོན་གྱིས་དུམ་བུ་དུམ་བུར་གཏུབས་ལ། དུམ་བུ་དེ་དང་ཨ་རུ་རའམ་བ་གཅིན་གྱི་ནང་དུ་ཞག་བདུན་གྱི་བར་དུ་ལེགས་པར་སྦངས་
ཚེག་འཇོག་རོགས།

2019-03-23 01:58 UTC, rekongrabten approved these changes

2019-03-23 01:59 UTC, merged