9/3/19 today
Esukhia/derge-tengyur pull request #6
Opened 2019-03-19 04:48 UTC by kungagyaltsen

2019-03-19 14:26 UTC, rekongrabten requested changes
འདི་དག་ལ་བསྐྱར་དུ་གཟིགས་རོགས། 2019-3-19

2019-03-19 14:26 UTC, rekongrabten commented on text/023_རྒྱུད་འགྲེལ།_ཟ.txt
> +[22b.1]བ་རྣམས་ལ་སངས་རྒྱས་ཀྱི་སྟེ། སྤྲུལ་བ་སྐུའི་གཟུགས་འཛིན་པའོ། །བསྐལ་པ་བཟང་པོ་པ་ཐམས་ཅད་ལ་མེད་དོ། །དེ་ནས་རིགས་ལྔ་རྣམས་ཀྱིས། །ཨོཾ་སརྦ་ཏཐཱ་ག་ཏ་ཨ་བྷི་ཥེ་ཀ་ས་མ་ཡ་ཤྲཱི་ཡེ་ཧཱུཾ་ཞེས་བརྗོད་ནས་བདག་པོ་རྣམས་ལ་ཐ
འདིའི་སྔ་ཕྱི་ལ་གཟིགས་རོགས།

2019-03-19 14:26 UTC, rekongrabten commented on text/079_རྒྱུད་འགྲེལ།_ཚུ.txt
> +[120a.5]པ་རྣམ་པར་སྣང་མཛད་འོད་ཀྱི་རྒྱལ་པོས་གསུངས་ཏེ། ཕན་ཡོན་ཆེན་པོ་དང་ལྡན་པའི་གཟུངས་སོ། །ཡེ་དྷརྨཱ་ཧེ་ཏུ་པྲ་བྷ་བཱ་ཧེ་ཏུནྟེ་ཥཱ་ནྟ་ཐཱ་ག་ཏོ་ཧྱ་བ་དཏ། ཏེ་ཥཱ་སྩ་ཡོ་ནི་རོདྷ་ཨེ་བཾ་བཱ་དཱི་མ་ཧཱ་ཤྲ་མ་ཎཿ། ཞེས་བྱ་བ
འདི་ལ་བསྐྱར་དུ་གཟིགས་རོགས།

2019-03-19 14:26 UTC, rekongrabten commented on text/171_འཁྲི་ཤིང།_ཁེ.txt
> +[311a.3]ཨི་ཏི་པྲ་ལཱ་ས་མུ་ཁ་རཿཔྲ་སརྦྦ་ན་རུ་ཌཱ་ནྟི་ཀཾ། །ཛཱི་མཱུ་ཏ་ཀེ་ཏུ་མཱ་ཡཱནྟཾ་མ་པ་ྶཱ་ནུ་གཾ་ཕ་ཎཱི། །ཏ་སྨཻ་ནི་བཻ་དྱ་བྲྀཏྟཱནྟཾ་ནཱ་གཿཤོ་ཀ་བི་ཤྲྀཾ་ཁ་ལཿ། །བ་བྷཱ་ཥེ་བྷུ་ཛ་མུཊྐྵི་སྱ་པཱཀྵེ་བཿཔ་ཀྵ་པུངྒ་ལཾ། །
འདི་གསུབ་ནོར་ཤོར་འདུག

2019-03-19 14:26 UTC, rekongrabten commented on text/196_སྒྲ་མདོ།_ཤེ.txt
> +[117b.3]བསྒྱུར་གཞན་ལས་ཞེས་པས་རྟག་ཏུ་ཡནའོ། །ཨཱ་ཡ་སྱ་ཏེ། པྲ་ཡས་ཏི་ཞེས་པའོ། །ཛ་སུ་ཐར་པ་ལའོ། །ཛ་སྱ་ཏི། ཏ་སུ་ད་སུ་ཉེ་བར་འདོར་བ་ལའོ། །ཏ་སྱ་ཏི། ད་སྱ་ཏི། བ་སུ་རེངས་པ་ལའོ། །བ་སྱ་ཏི། ཥ་རྣམ་པར་འབྱེད་པ་ལའོ། །པྱུ
འདི་གསུབ་མི་ཉན།

2019-03-19 14:26 UTC, rekongrabten commented on text/197_སྒྲ་མདོ།_སེ.txt
> +[183b.1]མཱཿ། །བ་རི་བ་སྱ་ཏུ་ཤུ་ཤྲུ་ཥཱ་པ་རི་ཙཪྻཱཔྻུཔཱ་ས་ནཾ། །བྱ་ཛྱཱཉཊཱཊྱཱ་པཪྻ་ཊ་ནཾ་ཙཪྻཱ་ཏྭཱིཪྻཱ་པ་ཐ་སྠི་ཏིཿ། །ཨུ་པ་སྤཪྴ་སྟྭཱ་ཙ་མ་ན་མ་ཐ་མཽ་ན་མ་བྷཱ་ཥ་ཎཾ། །ཨ་ནུ་པཱུརྦྦཱི་སྟྲི་ཡཱཾ་བཱ་བྲྀཏ་པ་རི་པཱ་ཊཱི་ཨ་ནུ་
འདི་ལ་བསྐྱར་དུ་གཟིགས་རོགས།

2019-03-19 14:26 UTC, rekongrabten commented on text/198_གསོ་རིག_ཧེ.txt
> +[15b.4]ས་མནྟ་དུ་གྟ་དང་། སྦུག་དང་། བཛྲི་རི་དང་། ནི་ཤྲི་ཤ་པཏྟ་ཀ་དང་། དེ་དག་ནི་ཤི་རི་ཁ་ཎྜའི་རྣམ་གྲངས་སོ། །ཤཾ་ཁི་ནི་དང་། ཏིག་ཏ་ལ་དང་། ཙིད་ཙ་དང་། ཡ་པ་ཏིག་ཏ་དང་། ཨ་ཀྵ་པཱི་ད་ཀ་དང་། བ་ཡུ་ཕེ་ཕབ་དང་། བ་ཡུ་ར་ས་
འདི་ལ་བསྐྱར་དུ་གཟིགས་རོགས།

2019-03-19 14:26 UTC, rekongrabten commented on text/207_སྣ་ཚོགས།_ཉོ.txt
> +[25b.7]པ་ནི། ལས་ཡོད་ན་དེའི་དབང་གིས་ཚེ་རབས་གཞན་དུ་འགྲོ་བ་ལྔར་སེམས་ཅན་སྐྱེ་བར་འགྱུར་གྱི། ལས་མེད་ན་ནི་ཉོན་མོངས་པ་ཡོད་ཀྱང་གྲོགས་མེད་པས་སྐྱེ་བར་མི་ནུས་སོ། །རྣམ་པར་ཤེས་པའི་རྐྱེན་དུ་འགྱུར་བ་ནི་ལས་ཀྱི་བག་ལ་ཉ
འདིའི་ཚིག་མཐའི་གིས  རྒྱབ་ཏུ་ཤད་ཅིག་འཇོག་རོགས།

2019-03-19 14:26 UTC, rekongrabten commented on text/207_སྣ་ཚོགས།_ཉོ.txt
> +[30b.3]པ་དང་། སྡུག་བསྔལ་བ་དང་། མི་གཙང་བ་དང་། བདག་མེད་པར་ཡོད་པའི་དངོས་པོ་ནི་མི་མཐོང་གི། རྟག་པ་དང་། བདེ་བ་དང་། གཙང་བ་དང་། བདག་ཅེས་བྱ་བ་མེད་པའི་དངོས་པོ་ཡོད་པར་མཐོང་བས་དེ་ནི་མ་རིག་པ་ཞེས་བྱའོ། །མ་རིག་པའི་
འདི་ལ་བསྐྱར་ནན་གྱིས་གཟིགས་རོགས།

2019-03-19 14:26 UTC, rekongrabten commented on text/209_སྣ་ཚོགས།_ཐོ.txt
> +[162b.7]ཡིད་མི་བདེ་བ་རྣམ་པར་སྨིན་པ་དང་བཅས་པ་ཁོ་ན་ཡིན་ནོ་ཞེས་བྱ་བ་གང་ཡིན་འོན་ཏེ་སྒྲའི་རིམ་པ་ཐ་དད་པས་ནི་པ་འདི་ལ་རྒྱུ་ཅི་ཞིག་ཡོད་ཅེ་ན།། དེའི་གསལ་བ་ཐ་དག །ཕྱིར་དེ་ནི་ལུང་དུ་མ་བསྟན་པ་ཡང་མེད་ལ་ཞེས་བྱ་བ་རྒྱ་
འདི་དག་དང་པོ་གང་ཡོད་པ་རང་འཇགས་འཇོག་རོགས།

2019-03-20 13:45 UTC, rekongrabten requested changes
འདི་དག་ལ་ཡང་གཟིགས་རོགས།

2019-03-20 13:45 UTC, rekongrabten commented on text/023_རྒྱུད་འགྲེལ།_ཟ.txt
> +[22b.1]བ་རྣམས་ལ་སངས་རྒྱས་ཀྱི་སྟེ། སྤྲུལ་བ་སྐུའི་གཟུགས་འཛིན་པའོ། །བསྐལ་པ་བཟང་པོ་པ་ཐམས་ཅད་ལ་མེད་དོ། །དེ་ནས་རིགས་ལྔ་རྣམས་ཀྱིས། །ཨོཾ་སརྦ་ཏཐཱ་ག་ཏ་ཨ་བྷི་ཥེ་ཀ་ས་མ་ཡ་ཤྲཱི་ཡེ་ཧཱུཾ་ཞེས་བརྗོད་ནས་བདག་པོ་རྣམས་ལ་ཐ
ཡང་བསྐྱར་དུ་གཟིགས་རོགས།

2019-03-20 13:45 UTC, rekongrabten commented on text/029_རྒྱུད་འགྲེལ།_ས.txt
> +[195b.5]སོགས་པའི་ཕྱག་མཚན་གྱིས་ཉེ་བར་མཚོན་པའོ། །ཙ་ཏུརྦྷུ་ཛ་ཙ་ཏུ་རྨུ་ཁ་ཥ་ཊ་ཙ་ར་ཎ་ཞེས་བྱ་བ་ལ། ཕྱག་བཞི་དང་ཞལ་བཞི་དང་ཞབས་དྲུག་གི་གཟུགས་ཀྱི་བདག་ཉིད་ཆེ་བས་སྣ་ཚོགས་པ་ཉིད་བསྟན་པ་སྟེ། འདིར་ནི་ཞལ་གསུམ་ཕྱག་དྲུག་
འདི་ལ་བསྐྱར་དུ་གཟིགས་རོགས།

2019-03-20 13:45 UTC, rekongrabten commented on text/079_རྒྱུད་འགྲེལ།_ཚུ.txt
> +[120a.5]པ་རྣམ་པར་སྣང་མཛད་འོད་ཀྱི་རྒྱལ་པོས་གསུངས་ཏེ། ཕན་ཡོན་ཆེན་པོ་དང་ལྡན་པའི་གཟུངས་སོ། །ཡེ་དྷརྨཱ་ཧེ་ཏུ་པྲ་བྷ་བཱ་ཧེ་ཏུནྟེ་ཥཱ་ནྟ་ཐཱ་ག་ཏོ་ཧྱ་བ་དཏ། ཏེ་ཥཱ་སྩ་ཡོ་ནི་རོདྷ་ཨེ་བཾ་བཱ་དཱི་མ་ཧཱ་ཤྲ་མ་ཎཿ། ཞེས་བྱ་བ
བསྐྱར་དུ་གཟིགས་རོགས།

2019-03-20 13:45 UTC, rekongrabten commented on text/196_སྒྲ་མདོ།_ཤེ.txt
> +[117b.3]བསྒྱུར་གཞན་ལས་ཞེས་པས་རྟག་ཏུ་ཡནའོ། །ཨཱ་ཡ་སྱ་ཏེ། པྲ་ཡས་ཏི་ཞེས་པའོ། །ཛ་སུ་ཐར་པ་ལའོ། །ཛ་སྱ་ཏི། ཏ་སུ་ད་སུ་ཉེ་བར་འདོར་བ་ལའོ། །ཏ་སྱ་ཏི། ད་སྱ་ཏི། བ་སུ་རེངས་པ་ལའོ། །བ་སྱ་ཏི། སྤུ་ཥ་རྣམ་པར་འབྱེད་པ་ལའོ།
འདི་ལ་བསྐྱར་དུ་གཟིགས་རོགས།

2019-03-20 13:45 UTC, rekongrabten commented on text/198_གསོ་རིག_ཧེ.txt
> +[15b.4]ས་མནྟ་དུ་གྟ་དང་། སྦུག་དང་། བཛྲི་རི་དང་། ནི་ཤྲི་ཤ་པཏྟ་ཀ་དང་། དེ་དག་ནི་ཤི་རི་ཁ་ཎྜའི་རྣམ་གྲངས་སོ། །ཤཾ་ཁི་ནི་དང་། ཏིག་ཏ་ལ་དང་། ཙིད་ཙ་དང་། ཡ་པ་ཏིག་ཏ་དང་། ཨ་ཀྵ་པཱི་ད་ཀ་དང་། བ་ཡུ་ཕེ་ཕབ་དང་། བ་ཡུ་ར་ས་
འདི་ལ་བསྐྱར་དུ་གཟིགས་རོགས།

2019-03-20 13:45 UTC, rekongrabten commented on text/207_སྣ་ཚོགས།_ཉོ.txt
> +[25b.7]པ་ནི། ལས་ཡོད་ན་དེའི་དབང་གིས་ཚེ་རབས་གཞན་དུ་འགྲོ་བ་ལྔར་སེམས་ཅན་སྐྱེ་བར་འགྱུར་གྱི། ལས་མེད་ན་ནི་ཉོན་མོངས་པ་ཡོད་ཀྱང་གྲོགས་མེད་པས་སྐྱེ་བར་མི་ནུས་སོ། །རྣམ་པར་ཤེས་པའི་རྐྱེན་དུ་འགྱུར་བ་ནི་ལས་ཀྱི་བག་ལ་ཉ
འདི་ལ་བསྐྱར་དུ་གཟིགས་རོགས། དབང་
གིས། འདི་ལྟར་བཟོ་རོགས།

2019-03-20 13:45 UTC, rekongrabten commented on text/207_སྣ་ཚོགས།_ཉོ.txt
> +[30b.3]པ་དང་། སྡུག་བསྔལ་བ་དང་། མི་གཙང་བ་དང་། བདག་མེད་པར་ཡོད་པའི་དངོས་པོ་ནི་མི་མཐོང་གི། རྟག་པ་དང་། བདེ་བ་དང་། གཙང་བ་དང་། བདག་ཅེས་བྱ་བ་མེད་པའི་དངོས་པོ་ཡོད་པར་མཐོང་བས་དེ་ནི་མ་རིག་པ་ཞེས་བྱའོ། །མ་རིག་པའི་
འདི་  ཅེས་བྱ་བ་
འདུ་བྱེད་  འདི་ལྟར་བཟོ་རོགས།

2019-03-21 13:47 UTC, rekongrabten requested changes
ཁྱེད་ཀྱིས་ནོར་འཁྲུལ་གང་ཡོད་པ་དག་ངེས་པར་བཟོ་རོགས། ནོར་འཁྲུལ་ཁག་མ་སེལ་བར་གང་བཟོས་ཀྱང་དང་ལེན་བྱེད་མི་ཐུབ། 2019-3-21

2019-03-21 13:47 UTC, rekongrabten commented on text/014_རྒྱུད་འགྲེལ།_པ.txt
> +[171a.2]ཧཱུཾ་ཧོཿརཱ་ཧུ་ཀཱ་ལཱ་གྣི་ཙནྡྲ་སཱུ་ཪྻ་བུདྡྷ་མཾ་ག་ལ་ཤུ་ཀྲ་པྲྀ་ཧ་སྤ་ཏི་ཀེ་ཏུ་ཤ་ནེ་བྷྱཿ། ཞེས་པ་ལ་སོགས་པ་གཟའི་གཏོར་མའི་སྔགས་སོ། །ཨོཾ་ཨཱཿཧཱུཾ་ཧོཿཛ་ཡ་བི་ཛ་ཡ་པདྨ་ཀ་རྐོ་ཊ་ག་བཱ་སུ་ཀིཾ་ཤཾ་ཁཱ་པཱ་ལ་ཀུ་ལི་ཀ
བསྐྱར་དུ་གཟིགས་རོགས།

2019-03-21 13:47 UTC, rekongrabten commented on text/014_རྒྱུད་འགྲེལ།_པ.txt
> +[171a.1]ཨཱ་ཀཱ་ཤ་ཝཱ་ཡུ་ཏེ་ཛ་ཨུ་ད་ཀ་པྲྀ་ཐྭཱི་སཱ་དྷི་ཏེ་བྷྱཿས་པ་རི་ཝཱ་རེ་ཞེས་པ་ལ་སོགས་པ་ལྷག་མ་སྔ་མ་བཞིན་ཏེ་ཟད་པར་གྱི་གཏོར་མའི་སྔགས་སོ། །ཨོཾ་ཨཱཿཧཱུཾ་ཧོཿབྲ་ཧྨ་བྷིཥྞཱུ་ནཻ་རྲྀ་ཏྱ་བཱ་ཡུ་ཡཱ་མཱ་ས་མུ་དྲེ་ཤྭཱ་རེ
འདི་ལ་ཡང་བསྐྱར་དུ་གཟིགས་རོགས།

2019-03-21 13:47 UTC, rekongrabten commented on text/016_རྒྱུད་འགྲེལ།_བ.txt
> +[264a.1]ཨོཾ་མ་ཧཱ་ཀ་ལྤཱ་གྣི་སཾ་ནི་བྷཱ་ཡ་ཧུཾ་ཧཱུཾ་ཕཊ། ཨོཾ་ཛ་ཊ་མུ་ཀུ་ཊོ་ཏ་ཀ་ཊཱ་ཡ་ཧུཾ་ཧཱུཾ་ཕཊ། ཨོཾ་དཾ་ཥྚཱ་ཀ་རཱ་ལོ་གྲ་བྷཱི་ཥ་ཎ་མུ་ཁཱ་ཡ་ཧུཾ་ཧཱུཾ་ཕཊ། ཨོཾ་ས་ཧ་སྲཱ་བྷུ་ཛ་བྷཱ་སུ་རཱ་ཡ་ཧུཾ་ཧཱུཾ་ཕཊ། ཨོཾ་པར་ཤུ་པཱ་
འདི་ལ་བསྐྱར་དུ་གཟིགས་རོགས།

2019-03-21 13:47 UTC, rekongrabten commented on text/022_རྒྱུད་འགྲེལ།_ཞ.txt
> +[137b.4]སྭཱ་ཧཱ། དཔའ་མོ་རྣམས་ཀྱི་སྔགས་སོ། །ཨོཾ་ན་མོ་བྷ་ག་བ་ཏི་ཝཱི་རེ་ཤཱ་ཡ། མ་ཧཱ་ཀལྤཱ་གྣི་སཾ་ནི་བྷཱ་ཡ། ཛཱ་ཊ་མ་ཀུ་ཊོ་ཊྐ་ཊཱ་ཡ། དཾཥྚྲ་ཀ་རཱ་ལོ་གྲ་བྷཱི་ཥ་ཎ་མུ་ཁཱ་ཡ། ས་ཧ་སྲ་བྷུ་ཛ་བྷཱ་སུ་རཱ་ཡི། བ་ར་ཤུ་པཱ་ཤོ་ད
བསྐྱར་དུ་གཟིགས་རོགས

2019-03-21 13:47 UTC, rekongrabten commented on text/022_རྒྱུད་འགྲེལ།_ཞ.txt
>  [142b.7]ཧཱུཾ་ཧཱུཾ་ཕཊ་ཕཊ་སྭཱ་ཧཱ། ཕྲེང་བའི་སྔགས་སོ། །དེ་ནས་ཇི་ལྟ་བ་བཞིན་སྦྱངས་པའི་གཏོར་མ་བཏང་སྟེ། རྣལ་འབྱོར་པ་ལྷོ་ཕྱོགས་སུ་མངོན་པར་ཕྱོགས་པས། མཐོན་པའི་ཕྱོགས་སུ་མཆོད་པར་བྱ། །མཚན་མོ་སྐྲ་གྲོལ་གཅེར་བུ་ཡིས།
བསྐྱར་དུ་གཟིགས་རོགས།

2019-03-21 13:47 UTC, rekongrabten commented on text/022_རྒྱུད་འགྲེལ།_ཞ.txt
> +[281a.6]ཨོཾ་མ་ཧཱ་ཀ་ལྤཱ་གྣི་སནྣི་བྷཱ་ཡ་ཧཱུཾ་ཧཱུཾ་ཕཊ། ཨོཾ་ཛཱ་ཊ་མུ་ཀུ་ཊོཏྐ་ཊཱ་ཡ་ཧཱུཾ་ཧཱུཾ་ཕཊ། ཨོཾ་དཾཥྚཱ་ཀ་རཱ་ལོ་གྲ་བྷི་ཥ་ཎ་མུ་ཁཱ་ཡ་ཧཱུཾ་ཧཱུཾ་ཕཊ། ཨོཾ་ས་ཧ་སྲ་བྷུ་ཛ་བྷ་སུ་རཱ་ཡ་ཧཱུཾ་ཧཱུཾ་ཕཊ། ཨོཾ་པ་ར་ཤུ་པཱ་ཤ
བསྐྱར་དུ་གཟིགས་རོགས།

2019-03-21 13:47 UTC, rekongrabten commented on text/023_རྒྱུད་འགྲེལ།_ཟ.txt
> +[22b.1]བ་རྣམས་ལ་སངས་རྒྱས་ཀྱི་སྟེ། སྤྲུལ་བ་སྐུའི་གཟུགས་འཛིན་པའོ། །བསྐལ་པ་བཟང་པོ་པ་ཐམས་ཅད་ལ་མེད་དོ། །དེ་ནས་རིགས་ལྔ་རྣམས་ཀྱིས། །ཨོཾ་སརྦ་ཏཐཱ་ག་ཏ་ཨ་བྷི་ཥེ་ཀ་ས་མ་ཡ་ཤྲཱི་ཡེ་ཧཱུཾ་ཞེས་བརྗོད་ནས་བདག་པོ་རྣམས་ལ་ཐ
ཏཐཱ་འདི་གཉིས་ཀྱི་བར་དུ་ཚེག་ཡོད

2019-03-21 13:47 UTC, rekongrabten commented on text/029_རྒྱུད་འགྲེལ།_ས.txt
> +[195b.5]སོགས་པའི་ཕྱག་མཚན་གྱིས་ཉེ་བར་མཚོན་པའོ། །ཙ་ཏུརྦྷུ་ཛ་ཙ་ཏུ་རྨུ་ཁ་ཥ་ཊ་ཙ་ར་ཎ་ཞེས་བྱ་བ་ལ། ཕྱག་བཞི་དང་ཞལ་བཞི་དང་ཞབས་དྲུག་གི་གཟུགས་ཀྱི་བདག་ཉིད་ཆེ་བས་སྣ་ཚོགས་པ་ཉིད་བསྟན་པ་སྟེ། འདིར་ནི་ཞལ་གསུམ་ཕྱག་དྲུག་
བསྐྱར་དུ་གཟིགས་རོགས།

2019-03-21 13:47 UTC, rekongrabten commented on text/079_རྒྱུད་འགྲེལ།_ཚུ.txt
> +[120a.5]པ་རྣམ་པར་སྣང་མཛད་འོད་ཀྱི་རྒྱལ་པོས་གསུངས་ཏེ། ཕན་ཡོན་ཆེན་པོ་དང་ལྡན་པའི་གཟུངས་སོ། །ཡེ་དྷརྨཱ་ཧེ་ཏུ་པྲ་བྷ་བཱ་ཧེ་ཏུནྟེ་ཥཱ་ནྟ་ཐཱ་ག་ཏོ་ཧྱ་བ་དཏ། ཏེ་ཥཱ་སྩ་ཡོ་ནི་རོདྷ་ཨེ་བཾ་བཱ་དཱི་མ་ཧཱ་ཤྲ་མ་ཎཿ། ཞེས་བྱ་བ
བསྐྱར་དུ་གཟིགས་རོགས།

2019-03-21 13:47 UTC, rekongrabten commented on text/156_འདུལ་བ།_ཙུ.txt
> +[309a.1]པའི་མཐིལ་ཡན་ཆད་ཅེས་བྱ་བ་ནི་རྐང་མཐིལ་གཉིས་ཡན་ཆད་ནས་སོ། །གླད་པའི་སྐྲ་མན་ཆད་ཅེས་བྱ་བ་ནི་སྐྲས་{མཆོན་,མཚོན}པའི་གླད་པ་མན་ཆད་དོ། །པགས་པ་ལ་ཐུག་པའི་ཞེས་བྱ་བ་ནི་པགས་པའི་མཐའིའོ། །བར་དུ་ཞེས་བྱ་བ་ནི་ཆུ་ཞེ
རྟགས་འདི་གང་ཡིན་ནམ། དོགས་རྟགས་ཡིན་ན་[མཆོན་] རྟགས་འདི་དང་ནོར་བཅོས་ཡིན་ན་(མཆོན་,མཚོན་) འདི་ལྟར་བཀོད་དགོས། གང་ཡིན་པ་དེ་བཀོད་རོགས།

2019-03-21 13:47 UTC, rekongrabten commented on text/194_སྒྲ་མདོ།_རེ.txt
> +[100a.7]ནོ་དེ་བ་ད་སྟེ་ན། པཱི་ཋ་ཡ་ཏི་བྱ། པཱ་ཋ་ནཱི་ཡ་པཱཥྱ། པཱ་ཋི་ཏོ། མཱ་ན་བ་ཀོ་བེ་ད་མུ་པཱ་དྷྱཱ་ཡེ་ན། པཱ་ཋ་ཡི་ཏ་བྱཿ། པཱ་ཋ་ནཱི་ཡཿ། པཱ་ཋྱ། པཱ་ཋི་ཏོ། མཱ་ན་པ་ཀཾ་བེ་ད་ཨུ་པཱ་དྷྱཱ་ཡེ་ན། ཨ་དྷྱཱ་པ་ཡི་ཏ་བྱོ྅། དྷྱ
འདི་ལ་བསྐྱར་དུ་གཟིགས་རོགས། ནོ་དེ་བ་དཏྟེ་ན།  ཞེས་གསལ།

2019-03-21 13:47 UTC, rekongrabten commented on text/196_སྒྲ་མདོ།_ཤེ.txt
> +[117b.3]བསྒྱུར་གཞན་ལས་ཞེས་པས་རྟག་ཏུ་ཡནའོ། །ཨཱ་ཡ་སྱ་ཏེ། པྲ་ཡས་ཏི་ཞེས་པའོ། །ཛ་སུ་ཐར་པ་ལའོ། །ཛ་སྱ་ཏི། ཏ་སུ་ད་སུ་ཉེ་བར་འདོར་བ་ལའོ། །ཏ་སྱ་ཏི། ད་སྱ་ཏི། བ་སུ་རེངས་པ་ལའོ། །བ་སྱ་ཏི། སྤུ་ཥ་རྣམ་པར་འབྱེད་པ་ལའོ།
འདི་ལ་བསྐྱར་དུ་ཡིན་ད

2019-03-21 13:47 UTC, rekongrabten commented on text/197_སྒྲ་མདོ།_སེ.txt
> +[147a.3]ལླཽ་སྱཱ་དཱ་བརྟྟོཉམྦྷ་སཱཾ་བྷྲ་མཿ། །པྲྀ་ཥནྟི་བིནྡུ་པྲི་ཥཏཱཿསུ་མཱཾ་སོ་བི་སྲུ་ཥཿསྟྲི་ཡཿ། །བ་ཀྲཱ་ཎི་པུ་ཀྲ་བྷེ་དཱཿསྱཱུ་བྷྲ་མཱཤྩ་ཛ་ལ་མཱཿ། །ཀཱུ་ལཾ་རོ་དྷཤྩ་ཏཱི་རཉྩ་པྲ་ཏཱི་རཉྩ་ཏ་ཊནྟྲི་ཥུ། །པཱ་རཱ་བཱ་རེ་
འདི་ལ་བསྐྱར་དི་གཟིགས་རོགས།

2019-03-21 13:47 UTC, rekongrabten commented on text/198_གསོ་རིག_ཧེ.txt
> +[15b.4]ས་མནྟ་དུ་གྟ་དང་། སྦུག་དང་། བཛྲི་རི་དང་། ནི་ཤྲི་ཤ་པཏྟ་ཀ་དང་། དེ་དག་ནི་ཤི་རི་ཁ་ཎྜའི་རྣམ་གྲངས་སོ། །ཤཾ་ཁི་ནི་དང་། ཏིག་ཏ་ལ་དང་། ཙིད་ཙ་དང་། ཡ་པ་ཏིག་ཏ་དང་། ཨ་ཀྵ་པཱི་ད་ཀ་དང་། བ་ཡུ་ཕེ་ཕབ་དང་། བ་ཡུ་ར་ས་
འདི་ལ་ཡང་བསྐྱར་དུ་གཟིགས་རོགས།

2019-03-21 13:47 UTC, rekongrabten commented on text/198_གསོ་རིག_ཧེ.txt
> +[28b.5]དང་། དི་བ་ད་དང་། ལོ་ཧི་ཏ་དང་། གྲི་མི་ཛ་དང་། ཛ་རུ་དང་། ཤ་ཏ་གྣི་དང་། རངྒ་མ་ཏ་དང་། དུ་མ་བྱ་ཏི་དང་། ཨ་ལཀྟ་ཀ་དང་། དེ་དག་ནི་རྒྱ་སྐྱེགས་ཀྱི་མིང་ངོ་། །ཧ་བྷིད་ཧཻ་དྷ་དང་། ཤ་ར་ད་དང་། ཤ་གུ་ལ་ད་ནི་དང་། མཉྫ
འདི་ལ་བསྐྱར་དུ་གཟིགས་རོགས། ཤ་ཏགྣི་དང་། ཞེས་གསལ།

2019-03-21 13:47 UTC, rekongrabten commented on text/207_སྣ་ཚོགས།_ཉོ.txt
> +[25b.7]པ་ནི། ལས་ཡོད་ན་དེའི་དབང་གིས་ཚེ་རབས་གཞན་དུ་འགྲོ་བ་ལྔར་སེམས་ཅན་སྐྱེ་བར་འགྱུར་གྱི། ལས་མེད་ན་ནི་ཉོན་མོངས་པ་ཡོད་ཀྱང་གྲོགས་མེད་པས་སྐྱེ་བར་མི་ནུས་སོ། །རྣམ་པར་ཤེས་པའི་རྐྱེན་དུ་འགྱུར་བ་ནི་ལས་ཀྱི་བག་ལ་ཉ
དབང་། 
གིས། ཞེས་བཟོ་རོགས་མཁྱེན།

2019-03-21 13:47 UTC, rekongrabten commented on text/207_སྣ་ཚོགས།_ཉོ.txt
> +[30b.3]པ་དང་། སྡུག་བསྔལ་བ་དང་། མི་གཙང་བ་དང་། བདག་མེད་པར་ཡོད་པའི་དངོས་པོ་ནི་མི་མཐོང་གི། རྟག་པ་དང་། བདེ་བ་དང་། གཙང་བ་དང་། བདག་ཅེས་བྱ་བ་མེད་པའི་དངོས་པོ་ཡོད་པར་མཐོང་བས་དེ་ནི་མ་རིག་པ་ཞེས་བྱའོ། །མ་རིག་པའི་
འདུ་བྱེད་རེད་ཡ།

2019-03-21 13:47 UTC, rekongrabten commented on text/208_སྒྲ་མདོ།_ཏོ.txt
> +[2b.2]བྲ་ལས་ཨཱུ་ཧཿ ཨཱུ་ཌྷཿ ཨཱུཌྷིཿ ཨེ་ཥཿ ཨེ་ཥྱ་རྣམས་ལའོ། །རྀ་ཏ་ལའང་གསུམ་པའི་ཚིག་སྡུད་ལའོ། །བྲ་བཏྨཿ བཏྤ་ཏ་རཿ ཀ་མཱ་ལཿ བ་ ད་ཤཿ རྀ་ཎ་རྣམས་ཀྱི་རྀ་ཎ་ལའོ། །ཉེར་བསྒྱུར་ལས་བྱིངས་རི་ཏ་ལ་ལའོ། །ཨཱ་པི་ཤ་ལིའི་སུ་ད
འདི་གསུབ་མི་རུང་།

2019-03-21 13:47 UTC, rekongrabten commented on text/209_སྣ་ཚོགས།_ཐོ.txt
> +[162b.7]ཡིད་མི་བདེ་བ་རྣམ་པར་སྨིན་པ་དང་བཅས་པ་ཁོ་ན་ཡིན་ནོ་ཞེས་བྱ་བ་གང་ཡིན་པ་འདི་ལ་རྒྱུ་ཅི་ཞིག་ཡོད་ཅེ་ན།། དེའི་ཕྱིར་དེ་ནི་ལུང་དུ་མ་བསྟན་པ་ཡང་མེད་ལ་ཞེས་བྱ་བ་རྒྱ་ཆེར་འབྱུང་སྟེ། །ས་བོན་རུལ་བ་བཞིན་ལུང་དུ་མ་
འདི་ལ་ཤད་གཉིས་མེད།

2019-03-22 04:08 UTC, kungagyaltsen commented on text/014_རྒྱུད་འགྲེལ།_པ.txt
> +[171a.2]ཧཱུཾ་ཧོཿརཱ་ཧུ་ཀཱ་ལཱ་གྣི་ཙནྡྲ་སཱུ་ཪྻ་བུདྡྷ་མཾ་ག་ལ་ཤུ་ཀྲ་པྲྀ་ཧ་སྤ་ཏི་ཀེ་ཏུ་ཤ་ནེ་བྷྱཿ། ཞེས་པ་ལ་སོགས་པ་གཟའི་གཏོར་མའི་སྔགས་སོ། །ཨོཾ་ཨཱཿཧཱུཾ་ཧོཿཛ་ཡ་བི་ཛ་ཡ་པདྨ་ཀ་རྐོ་ཊ་ག་བཱ་སུ་ཀིཾ་ཤཾ་ཁཱ་པཱ་ལ་ཀུ་ལི་ཀ
གནི་> གྣི་  ལབ་ས་དེ་ཨ་མ་ནང་བཞིན་བཟོ་ཡོད་ཁྱེད་ཀྱི་ཨ་མ་ལ་གཟིགས་ཀྱི་མེད་པ་འདྲ།

2019-03-23 01:46 UTC, rekongrabten requested changes
2019-3-22 འདི་དག་ལ་བསཀྻར་དུ་བལྟ་དགོས་པ་དང། གཞན་སྔོན་བཀོད་ཀྱི་མཆན་ཁ་ཤས་བཟོས་མེད་པས་དེ་དག་ངེས་པར་བཟོ་རོགས།

2019-03-23 01:46 UTC, rekongrabten commented on text/202_གསོ་རིག_གོ.txt
> +[266b.5]གྱུར་ན། །ཤས་ཆེར་ན་ཞིང་ཟུག་པར་བྱེད། །ཅེས་བྱ་བ་ལ། རླུང་གི་རང་བཞིན་ཅན་གྱི་སྲིན་བུས་ཟིན་པར་གྱུར་ན། ཚ་བ་ལ་སོགས་པས་མཚན་ལྷག་པར་ན་བ་དང་ཟུག་པར་བྱེད་པ་ཡིན་ནོ། །མེ་ཡི་སྲིན་བུས་འཛག་པ་ཆུང་། །ཚ་ཞིང་དམར་ལ་ཤ
འདི་གང་ཡིན་ནམ།

2019-03-23 01:46 UTC, rekongrabten commented on text/203_སྣ་ཚོགས།_ངོ.txt
> +[11a.4]པར་བརྒྱད་པ་གོ །མཉམ་དུ་འབྲེལ་པ་ནི་དང་པོའི་རྐང་པ་ལྟར་མ ཆད་པར་འདྲེལ་པའོ། །བྱའི་སྒོ་ང་ཞེས་བྱ་བ་ལ་སོགས་པས་ནི་ཞལ་རྣམ་པ་བཞི་རུ་གསུངས་སོ། །སྐྱེས་བུ་ཆེན་པོའི་ཞལ་ནི་བྱའི་སྒོ་ངའི་རྣམ་པའོ། །མཎྜལ་གྱི་རྣམ་པ
འདི་ཡང་

2019-03-23 01:46 UTC, rekongrabten commented on text/208_སྒྲ་མདོ།_ཏོ.txt
> +[91b.5]པའི་མདོག འཚོ་བམ། ཡ་དང་མ་ཡིན། ལྟ་བུ་སྐུད་པའི་དོན་ཡིན་ན་ཨ་ཨིར་འགྱུར་ལ། དོན་གཞན་ཡིན་ན་ནི་འགྱུར་ ལྷས་སྤྱིན་མ། [མཆད་སྦྱིན་,མཆོད་སྦྱིན]མ། རོ། །པ་རྟྟ་ཀཱ་ཞེས་པའང་ཤར་ཕྱོགས་ཀྱི་པཎྜི་ཏ་རྣམས་དེ་ཀར་གནས་ ཟད
རྟགས་གང་ཡིན་ནམ

2019-03-23 01:46 UTC, rekongrabten commented on text/208_སྒྲ་མདོ།_ཏོ.txt
> +[213a.4]སྠ་ལའོ། །པ་ཏ་བ་ཏཱི་ལྡུང་བ་ལའོ། བ་ད་ བད་འགྲོ་བ་ལ་རོ། །གཱུ་བྱིངས་དྷུའི་མིང་ཅན་[ཌུ]་དྷཱཉ་འཛིན་པ་དང་[ཌྱ་]དཱཉ་སྦྱིན་པ་གཉིས། མཱ་མང་[མཆད་,མ་ཆད ]བ་ལའོ། །སྱ་ཏི་ ཥོ་མཐའི་ལས་ལའོ། །ཧ་ནྟི་ ཧ་ན་འཚོ་བ་ལ་སྟེ
འདི་ག་རེ་ཡིན་ནམ

2019-03-25 03:45 UTC, kungagyaltsen commented on text/208_སྒྲ་མདོ།_ཏོ.txt
> +[91b.5]པའི་མདོག འཚོ་བམ། ཡ་དང་མ་ཡིན། ལྟ་བུ་སྐུད་པའི་དོན་ཡིན་ན་ཨ་ཨིར་འགྱུར་ལ། དོན་གཞན་ཡིན་ན་ནི་འགྱུར་ ལྷས་སྤྱིན་མ། [མཆད་སྦྱིན་,མཆོད་སྦྱིན]མ། རོ། །པ་རྟྟ་ཀཱ་ཞེས་པའང་ཤར་ཕྱོགས་ཀྱི་པཎྜི་ཏ་རྣམས་དེ་ཀར་གནས་ ཟད
དོག་རྟགས་ཡིན།

2019-03-26 09:22 UTC, rekongrabten approved these changes

2019-03-26 09:22 UTC, merged