2019-3-19
Esukhia/derge-tengyur pull request #7
Opened 2019-03-19 11:21 UTC by tseringwa

2019-03-19 13:59 UTC, rekongrabten requested changes
འདི་དག་ལ་བསྐྱར་དུ་གཟིགས་རོགས། 2019-3-19

2019-03-19 13:59 UTC, rekongrabten commented on text/151_འདུལ་བ།_ནུ.txt
> +[236a.5]ཉེས་བྱས་སོ། །དེ་ཡང་སྦྱོར་བའི་ཆོ་ག་ཡིན་ཏེ། བསླབ་པའི་གཞི་ཐམས་ཅད་དུ་ཡང་རིག་པར་བྱའོ། །གྱེན་དུ་འབྱུང་ངམ། བྱིའུ་ཟུལ་བྱས་སམ། ཕ་རོལ་དུ་འགྲོ་བ་འམ། ཚུ་རོལ་དུ་འོང་ངམ། ཆུའི་རྒྱུན་ནམ། སླར་གྱེན་དུ་རྐྱལ་ལམ།
འདི་འདྲི་ཡིན་པས་བསྐྱར་དུ་བཟོ་རོགས།

2019-03-19 13:59 UTC, rekongrabten commented on text/171_འཁྲི་ཤིང།_ཁེ.txt
> +[62a.6]ཆུང་མ་དང་། །ལྷན་ཅིག་ཁྱིམ་རྣམས་སུ་ཞུགས་གླུ་བླངས་པ། །སྐྱེ་བོ་བླ་མ་ཁྲོས་པས་རབ་བསྐྲུན་སྒྲ་གཅན་གྱི་ནི་མཐུ་ཡིས་ཉི་མ་རྣམ་པར་ཉམས་བྱས་ཤིང་། །བདེན་མེད་ཡོངས་སུ་སྨྲ་བའི་རྣམ་པར་བསླད་པ་ནག་ཕྱོགས་ཉིན་གྱིས་སྤྱ
འདི་ལ་དོགས་རྟགས་བཀོད་རོགས།

2019-03-19 13:59 UTC, rekongrabten commented on text/208_སྒྲ་མདོ།_ཏོ.txt
> +[263a.6]གསུམ་ལ། ཨ་བཀྵི། ཨ་བ་ཀྵཱ་ཧི། ཨ་བ་ཀྵྨ་ཧི། ལིཊ་ལ་ཀིཏ་མིན་པ་རྣམས་ལ། ལིཊ་ལ་གཉིས་རྣམས་ཀྱི་སོགས་ཀྱི་མདོས་ཨ་བྷྱཱས། སཾ་པྲ་སཱ་ར་ཎ་དང་། ཀིཏ་རྣམས་ལ་ཝ་ཙ་སྭ་པི་ཡ་ཛ་སོགས་ཀྱིས་གཉིས་ཀ་སཾ་པྲ་སཱ་ར་ཎ་ར་འགྱུར་བ་ས
འདིའི་བརྗོད་པ་བཀླག་རོགས།

2019-03-20 03:44 UTC, tseringwa commented on text/208_སྒྲ་མདོ།_ཏོ.txt
> +[263a.6]གསུམ་ལ། ཨ་བཀྵི། ཨ་བ་ཀྵཱ་ཧི། ཨ་བ་ཀྵྨ་ཧི། ལིཊ་ལ་ཀིཏ་མིན་པ་རྣམས་ལ། ལིཊ་ལ་གཉིས་རྣམས་ཀྱི་སོགས་ཀྱི་མདོས་ཨ་བྷྱཱས། སཾ་པྲ་སཱ་ར་ཎ་དང་། ཀིཏ་རྣམས་ལ་ཝ་ཙ་སྭ་པི་ཡ་ཛ་སོགས་ཀྱིས་གཉིས་ཀ་སཾ་པྲ་སཱ་ར་ཎ་ར་འགྱུར་བ་ས
མ་ཡིག་ནང་དུ་འགྱུར་རེད། བགྱུར་མིན་པ་འདུག

2019-03-20 13:19 UTC, rekongrabten requested changes
འདི་དག་ལ་བསྐྱར་དུ་གཟིགས་རོགས། 2019-3-20

2019-03-20 13:19 UTC, rekongrabten commented on text/202_གསོ་རིག_གོ.txt
> +[55b.7]ན་ཕན་པ་དང་། །དེ་བཞིན་དུ་གུ་གུལ་ཉི་ཚེའི་སྦྱོར་བ་བཏང་ན་ཕན་པ་དང་། །པ་བསངས་ཀྱིས་བཤད་པའི་བཅུད་ཀྱིས་ལེན་པའི་སྦྱོར་བ་ཇི་སྐད་བཤད་པ་དག་ཀྱང་ཕན་ཏེ། དེ་ནི་ཁ་ར་སྲང་སྟོང་ཆིག་བརྒྱ་དང་བཅས་པའི་ལྕགས་ཕྱེའི་སྦྱོར
འདི་ལ་བསྐྱར་དུ་གཟིགས་རོགས།

2019-03-20 13:19 UTC, rekongrabten commented on text/202_གསོ་རིག_གོ.txt
> +[65b.5]བྱིད་ཀྱི་ལྡེ་གུ་ཡང་བླུད་བར་བྱའོ། །དན་དའི་ཁུ་བར་དེ་ཡི་རྐང་། །བུ་རམ་རྙིང་པ་བཅུག་ནས་ནི། །ཟླ་བ་གཅིག་གམ་ཟླ་ཕྱེད་བར། །མནན་པའི་ཆང་ནི་བླུད་པར་བྱ། །ཞེས་བྱ་བ་ལ། དོང་གའི་རྐང་དང་བུ་རམ་རྙིང་བ་དན་ད་བསྐོལ་བའ
འདི་ལ་བསྐྱར་དུ་གཟིགས་རྒྱུ་དང་བརྗོད་པ་དེ་ཡང་ཀློག་རོགས།

2019-03-20 13:19 UTC, rekongrabten commented on text/202_གསོ་རིག_གོ.txt
> +[76b.3]ཆ་ཏིལ་མར། །ཐལ་སྨན་ལན་ཚྭར་བཅས་པ་ནི། །རིག་པའི་འཇམ་རྩི་བད་ཀན་ནད། །སྐྱ་རྦབ་གསུང་པའི་ནད་རྣམས་དང་། །ཁུ་བ་རླུང་ནི་འགགས་པ་དང་། །རླུང་འཁྲུགས་པ་ལ་བསྔགས་པ་ཡིན། །ཞེས་བྱ་བ་ལ། རྩ་བ་བཅུ་བ་ལ་སོགས་པའི་སྨན་ཚུལ་
འདི་ལ་བསྐྱར་དུ་གཟིགས་རོགས།

2019-03-20 13:19 UTC, rekongrabten commented on text/202_གསོ་རིག_གོ.txt
> +[90a.6]དེ་ནི་རྣ་བའི་དྲུང་དུ་ནི། །རྡོ་གཉིས་བརྡུང་བ་སྤྱད་པར་བྱ། །ཞེས་བྱ་བ་ལ། དེའི་འོག་ཏུ་རྣ་བ་སྦྱང་བའི་ཕྱིར་བྱིས་པ་དེའི་རྣ་བའི་དྲུང་དུ་རྡོ་གཉིས་བརྡབ་ཅིང་བརྡུང་བ་ཉེ་བར་སྤྱད་ཅིང་སྒྲ་བསྒྲགས་པར་བྱའོ། །དེ་ན
འདི་ལ་བསྐྱར་དུ་གཟིགས་རོགས།

2019-03-20 13:19 UTC, rekongrabten commented on text/202_གསོ་རིག_གོ.txt
> +[168b.2]རྩ་བ་དང་། མིག་མཆུའི་ཤ་དང་། སྐྱུར་གྱིས་བསྐྱེད་པ་དང་། ཅུང་ཟད་སྐྲངས་པ་དང་། མཁྲེས་པའི་མཆི་མ་འཛག་པ་དང་། ཁྲག་གི་མཆི་མ་འཛག་པ་དང་། བད་ཀན་གྱི་མཆི་མ་འཛག་པ་དང་། མཁྲིས་པའི་མིག་ནད་གདུང་བ་དང་། ཁྲག་གིས་གདུང
བསྐྱར་དུ་གཟིགས་རོགས།

2019-03-21 12:53 UTC, rekongrabten approved these changes

2019-03-21 12:53 UTC, merged