2019-3-21ནོར་སྤྱོད།
Esukhia/derge-tengyur pull request #9
Opened 2019-03-21 05:20 UTC by kunchokdolma

2019-03-21 12:40 UTC, rekongrabten requested changes
འདི་གཉིས་ལ་བསྐྱར་དུ་གཟིགས་རོགས། 2019-3-21

2019-03-21 12:40 UTC, rekongrabten commented on text/195_སྒྲ་མདོ།_ལེ.txt
> +[215b.3]གཉིས་བརྗོད་དོ། །བི་ཀ་ར་ཎ་ལ་ཨན་ཉིད་ལའོ། །མདོ་སྔ་མ་གཉིས་ཀྱི་ཤིན་ཏུ་བཞག་པའི་ཡོན་ཏན་བི་ཀ་ར་ཎ་ཐམས་ཅད་ལ་འགྱུར་རོ་ཞེས་པ་འགོག་པའོ། །བྱིངས་ཀྱི་ཡན་ཁོ་ནའི་བི་ཀ་ར་ཎ་ལ་ཡོན་ཏན་དུ་འགྱུར་རོ། །བྷ་བ་ཏི། །བྟབཏཿ
འདི་ལ་བསྐྱར་དུ་གཟིགས་རོགས།

2019-03-21 12:40 UTC, rekongrabten commented on text/203_སྣ་ཚོགས།_ངོ.txt
> +[92a.1]{D323}༄། །ཚེའི་གནས་སྐབས་ཀྱི་འབྲས་བུ་གནོད་པ་འབྱུང་བ་ཞེས་བྱ་བའི་ལས་བཞུགས་སོ།།  ༄༅༅། །འཕགས་པ་འཇམ་དཔལ་ལ་ཕྱག་འཚལ་ལོ། །གཟའི་གནོད་པ་སྤང་བའོ། །ཉི་མ་ལ་མེ་ལྟར་མཆོད་པར་བྱའོ། །ཟླ་བ་ལ་ཀླུ་མཆོད་པར་བྱའོ། །མི
འདིའི་ཆོས་ཨང་ནོར་ཡོད་པ་འདྲ།

2019-03-22 04:18 UTC, kunchokdolma commented on text/203_སྣ་ཚོགས།_ངོ.txt
> +[92a.1]{D323}༄། །ཚེའི་གནས་སྐབས་ཀྱི་འབྲས་བུ་གནོད་པ་འབྱུང་བ་ཞེས་བྱ་བའི་ལས་བཞུགས་སོ།།  ༄༅༅། །འཕགས་པ་འཇམ་དཔལ་ལ་ཕྱག་འཚལ་ལོ། །གཟའི་གནོད་པ་སྤང་བའོ། །ཉི་མ་ལ་མེ་ལྟར་མཆོད་པར་བྱའོ། །ཟླ་བ་ལ་ཀླུ་མཆོད་པར་བྱའོ། །མི
ཨ་ཁུ་ཀུན་འཇམ་གི་བསྐྱར་བཟོ་དེ་ངས་ནོར་ནས་སྤྱོད་འདུག

2019-03-23 01:36 UTC, rekongrabten requested changes
འདི་གཅིག་པུ་བསྐྱར་དུ་བཟོ་རོགས། 2019-3-22

2019-03-23 01:36 UTC, rekongrabten commented on text/203_སྣ་ཚོགས།_ངོ.txt
> +[92a.1]{D323}༄། །ཚེའི་གནས་སྐབས་ཀྱི་འབྲས་བུ་གནོད་པ་འབྱུང་བ་ཞེས་བྱ་བའི་ལས་བཞུགས་སོ།།  ༄༅༅། །འཕགས་པ་འཇམ་དཔལ་ལ་ཕྱག་འཚལ་ལོ། །གཟའི་གནོད་པ་སྤང་བའོ། །ཉི་མ་ལ་མེ་ལྟར་མཆོད་པར་བྱའོ། །ཟླ་བ་ལ་ཀླུ་མཆོད་པར་བྱའོ། །མི
འདིའི་ཆོས་ཨང་ནོར་འདུག {D4323}  ཡིན་དགོས་པས་4 ཆད་འདུག

2019-03-25 14:17 UTC, rekongrabten requested changes
འདི་དག་ལ་བསྐྱར་དུ་གཟིགས་རོགས། 2019-3-25

2019-03-25 14:17 UTC, rekongrabten commented on text/203_སྣ་ཚོགས།_ངོ.txt
> +[15b.6]ཚད་མཆན་ཉིད་ཀྱི། །སྒྲ་དོན་ལེགས་པའི་བསྒྱུར་བ་ཡིན།། {D4317}༅། །གྲུབ་ཐོབ་བརྒྱད་བཅུའི་མངོན་པར་རྟོགས་པ་བཞུགས།  ༄༅༅། །ཐམས་ཅད་མཁྱེན་པ་ལ་ཕྱག་འཚལ་ལོ། །ལཱུ་ཡི་པ་དུ་བའི་མདོག་ཅན། སྐྱེ་པ་དང་ལྷན་ཅིག་པའོ། །ལི
བཞུགས། ཞེས་པའི་རྒྱབ་ཏུ་སྟོང་པ་མེད་གཅིག་ལས་མེད།

2019-03-25 14:17 UTC, rekongrabten commented on text/203_སྣ་ཚོགས།_ངོ.txt
> +[15b.6]ཚད་མཆན་ཉིད་ཀྱི། །སྒྲ་དོན་ལེགས་པའི་བསྒྱུར་བ་ཡིན།། {D4317}༅། །གྲུབ་ཐོབ་བརྒྱད་བཅུའི་མངོན་པར་རྟོགས་པ་བཞུགས།  ༄༅༅། །ཐམས་ཅད་མཁྱེན་པ་ལ་ཕྱག་འཚལ་ལོ། །ལཱུ་ཡི་པ་དུ་བའི་མདོག་ཅན། སྐྱེ་པ་དང་ལྷན་ཅིག་པའོ། །ལི
ཆོས་ཚན་གྱི་དབུ་ཁྱུད་དེ་༄། ། འདི་ཡིན་པ་དང་བཞུགས།  ཞེས་པའི་རྒྱབ་ཏུ་སྟོང་པ་གཅིག་ལས་མེད།

2019-03-25 14:17 UTC, rekongrabten commented on text/203_སྣ་ཚོགས།_ངོ.txt
> +[18a.2]དྲུག་གི་བར་དུ་གྲུ་ལ་ཕྱིན་ན་འབྱིངས་བ་བསྲུང་སོ། །དབང་ཕྱུག་གིས་བསྟན་པའི་རིན་པོ་ཆེའི་བཅུད་ལེན་གྲུབ་པ་རྫོགས་སོ།། །།ཧ་རི་དྷོ་བར་གྱི་རྣལ་འབྱོར་བ་ཤི་བ་དཱ་ཤ་དང་། ཨུ་རྒྱན་པས་བུ་ཏྲར་བསྒྱུར་བའོ།། {D4319}༅
༄། ། ཆོས་མཚན་གྱི་མདུན་དུ་དབུ་ཁྱུད་འདི་འཇོག་རོགས།

2019-03-25 14:17 UTC, rekongrabten commented on text/203_སྣ་ཚོགས།_ངོ.txt
> +[18b.2]སྦྱར་བའི་མིག་མངས་རིས་ཀྱི་སྦྱོར་བ་ཚིག་ལེའུར་བྱས་པ་སློབ་དཔོན་ཀླུ་སྒྲུབ་ཀྱིས་མཛད་པ་བརྫོགས་སོ།། {D4320}༅། །སྤོས་ཀྱི་སྦྱོར་བ་རེའུ་ཆར་བྱས་པའི་ཐབས་བཤད་པ་བཞུགས། ༄༅༅། །དཀོན་མཆོག་གསུམ་ལ་ཕྱག་འཚལ་ལོ། །སྤོ
འདིའི་དབུ་ཁྱུད་ཀྱང་གཅིག་པ་ཡིན།

2019-03-25 14:17 UTC, rekongrabten commented on text/203_སྣ་ཚོགས།_ངོ.txt
> +[260a.4]འཇུག་པ་ན། །ནད་པ་མཐོང་བར་གྱུར་བ་དང་། །ལས་ནི་རྩོམ་པར་གྱུར་བའི་ཚེ། །འདིས་ནི་འགྲུབ་དང་མི་འགྲུབ་སྟོན། །འཆི་ལྟས་གསང་བའི་འདི་དག་ནི། །ཡང་དག་ཉིད་དུ་ཤེས་པར་བྱ། །འདི་དག་ཐམས་ཅད་གང་གིས་ནི། །ཡང་དག་ཤེས་ཏེ་ས
འདི་ལ་བསྐྱར་དུ་གཟིགས་རོགས། གྱུར་པ་དང་། །

2019-03-26 03:48 UTC, kunchokdolma commented on text/203_སྣ་ཚོགས།_ངོ.txt
> +[92a.1]{D323}༄། །ཚེའི་གནས་སྐབས་ཀྱི་འབྲས་བུ་གནོད་པ་འབྱུང་བ་ཞེས་བྱ་བའི་ལས་བཞུགས་སོ།།  ༄༅༅། །འཕགས་པ་འཇམ་དཔལ་ལ་ཕྱག་འཚལ་ལོ། །གཟའི་གནོད་པ་སྤང་བའོ། །ཉི་མ་ལ་མེ་ལྟར་མཆོད་པར་བྱའོ། །ཟླ་བ་ལ་ཀླུ་མཆོད་པར་བྱའོ། །མི
ཨ་ཁུ་ཀུན་འཇམ་གི་བསྐྱར་བཟོ་དེ་ངས་ནོར་ནས་སྤྱོད་འདུག

2019-03-26 09:58 UTC, rekongrabten approved these changes

2019-03-26 10:34 UTC, rekongrabten approved these changes

2019-03-26 10:37 UTC, rekongrabten approved these changes

2019-03-26 10:43 UTC, rekongrabten approved these changes

2019-03-26 10:44 UTC, merged

2019-03-26 10:44 UTC, rekongrabten commented
22225